// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "aStar_adjacentNodes.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic aStar_adjacentNodes::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic aStar_adjacentNodes::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<18> aStar_adjacentNodes::ap_ST_st1_fsm_0 = "1";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st2_fsm_1 = "10";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st3_fsm_2 = "100";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st4_fsm_3 = "1000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st5_fsm_4 = "10000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st6_fsm_5 = "100000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<18> aStar_adjacentNodes::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> aStar_adjacentNodes::ap_const_lv1_1 = "1";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_3 = "11";
const sc_lv<1> aStar_adjacentNodes::ap_const_lv1_0 = "0";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_6 = "110";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_B = "1011";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_1 = "1";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_2 = "10";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_7 = "111";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_8 = "1000";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_A = "1010";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_E = "1110";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_F = "1111";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_11 = "10001";
const sc_lv<3> aStar_adjacentNodes::ap_const_lv3_4 = "100";
const sc_lv<3> aStar_adjacentNodes::ap_const_lv3_6 = "110";
const sc_lv<3> aStar_adjacentNodes::ap_const_lv3_0 = "000";
const sc_lv<3> aStar_adjacentNodes::ap_const_lv3_2 = "10";
const sc_lv<3> aStar_adjacentNodes::ap_const_lv3_5 = "101";
const sc_lv<3> aStar_adjacentNodes::ap_const_lv3_7 = "111";
const sc_lv<3> aStar_adjacentNodes::ap_const_lv3_3 = "11";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_9 = "1001";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_10 = "10000";
const sc_lv<3> aStar_adjacentNodes::ap_const_lv3_1 = "1";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_3E = "111110";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_4 = "100";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_5 = "101";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_3F = "111111";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_23 = "100011";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_C = "1100";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_D = "1101";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_22 = "100010";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_FFFFFFBF = "11111111111111111111111110111111";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_FFFFFFC1 = "11111111111111111111111111000001";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_41 = "1000001";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_FFFFFFC0 = "11111111111111111111111111000000";
const sc_lv<32> aStar_adjacentNodes::ap_const_lv32_40 = "1000000";

aStar_adjacentNodes::aStar_adjacentNodes(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_adjacentPosition_0_address0);
    sensitive << ( tmp_7_fu_233_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_8_fu_238_p2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_adjacentPosition_0_address1);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_adjacentPosition_0_ce0);
    sensitive << ( tmp_7_fu_233_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_8_fu_238_p2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_adjacentPosition_0_ce1);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_adjacentPosition_0_d0);
    sensitive << ( x );
    sensitive << ( tmp_7_fu_233_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_8_fu_238_p2 );
    sensitive << ( tmp_10_fu_243_p2 );
    sensitive << ( tmp_11_reg_320 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_adjacentPosition_0_d1);
    sensitive << ( x );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_10_reg_315 );
    sensitive << ( tmp_11_fu_249_p2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_adjacentPosition_0_we0);
    sensitive << ( tmp_7_fu_233_p2 );
    sensitive << ( tmp_7_reg_307 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_8_fu_238_p2 );
    sensitive << ( tmp_8_reg_311 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_adjacentPosition_0_we1);
    sensitive << ( tmp_7_fu_233_p2 );
    sensitive << ( tmp_7_reg_307 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_8_fu_238_p2 );
    sensitive << ( tmp_8_reg_311 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_adjacentPosition_1_address0);
    sensitive << ( tmp_12_fu_255_p2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_13_fu_260_p2 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_adjacentPosition_1_address1);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_adjacentPosition_1_ce0);
    sensitive << ( tmp_12_fu_255_p2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_13_fu_260_p2 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_adjacentPosition_1_ce1);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_adjacentPosition_1_d0);
    sensitive << ( y );
    sensitive << ( tmp_12_fu_255_p2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_13_fu_260_p2 );
    sensitive << ( tmp_14_reg_333 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( tmp_15_fu_271_p2 );
    sensitive << ( tmp_15_reg_339 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_adjacentPosition_1_d1);
    sensitive << ( y );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_14_fu_265_p2 );
    sensitive << ( tmp_14_reg_333 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( tmp_15_reg_339 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_adjacentPosition_1_we0);
    sensitive << ( tmp_12_fu_255_p2 );
    sensitive << ( tmp_12_reg_325 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_13_fu_260_p2 );
    sensitive << ( tmp_13_reg_329 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_adjacentPosition_1_we1);
    sensitive << ( tmp_12_fu_255_p2 );
    sensitive << ( tmp_12_reg_325 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_13_fu_260_p2 );
    sensitive << ( tmp_13_reg_329 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_adjacentPosition_2_address0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );

    SC_METHOD(thread_adjacentPosition_2_address1);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );

    SC_METHOD(thread_adjacentPosition_2_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );

    SC_METHOD(thread_adjacentPosition_2_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );

    SC_METHOD(thread_adjacentPosition_2_d0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_3_fu_183_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_5_fu_197_p2 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_s_fu_209_p2 );
    sensitive << ( tmp_1_fu_221_p2 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );

    SC_METHOD(thread_adjacentPosition_2_d1);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( tmp_4_fu_190_p2 );
    sensitive << ( tmp_6_fu_203_p2 );
    sensitive << ( tmp_9_fu_215_p2 );
    sensitive << ( tmp_2_fu_227_p2 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );

    SC_METHOD(thread_adjacentPosition_2_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );

    SC_METHOD(thread_adjacentPosition_2_we1);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_ap_sig_bdd_113);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_126);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_136);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_145);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_156);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_165);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_174);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_183);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_192);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_201);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_225);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_238);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_260);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_268);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_324);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_332);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_36);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_92);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_bdd_225 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_bdd_174 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_bdd_126 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_bdd_324 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_bdd_332 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_bdd_183 );

    SC_METHOD(thread_ap_sig_cseq_ST_st16_fsm_15);
    sensitive << ( ap_sig_bdd_192 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_16);
    sensitive << ( ap_sig_bdd_238 );

    SC_METHOD(thread_ap_sig_cseq_ST_st18_fsm_17);
    sensitive << ( ap_sig_bdd_201 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_36 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_136 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_145 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_92 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_260 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_268 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_113 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_156 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_165 );

    SC_METHOD(thread_initPosition_fu_177_p2);
    sensitive << ( x );
    sensitive << ( tmp_fu_171_p2 );

    SC_METHOD(thread_tmp_10_fu_243_p2);
    sensitive << ( x );

    SC_METHOD(thread_tmp_11_fu_249_p2);
    sensitive << ( x );

    SC_METHOD(thread_tmp_12_fu_255_p2);
    sensitive << ( y );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_tmp_13_fu_260_p2);
    sensitive << ( y );
    sensitive << ( tmp_12_fu_255_p2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_tmp_14_fu_265_p2);
    sensitive << ( y );

    SC_METHOD(thread_tmp_15_fu_271_p2);
    sensitive << ( y );

    SC_METHOD(thread_tmp_1_fu_221_p2);
    sensitive << ( initPosition_reg_297 );

    SC_METHOD(thread_tmp_2_fu_227_p2);
    sensitive << ( initPosition_reg_297 );

    SC_METHOD(thread_tmp_3_fu_183_p2);
    sensitive << ( initPosition_fu_177_p2 );

    SC_METHOD(thread_tmp_4_fu_190_p2);
    sensitive << ( initPosition_fu_177_p2 );

    SC_METHOD(thread_tmp_5_fu_197_p2);
    sensitive << ( initPosition_reg_297 );

    SC_METHOD(thread_tmp_6_fu_203_p2);
    sensitive << ( initPosition_reg_297 );

    SC_METHOD(thread_tmp_7_fu_233_p2);
    sensitive << ( x );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_tmp_8_fu_238_p2);
    sensitive << ( x );
    sensitive << ( tmp_7_fu_233_p2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_tmp_9_fu_215_p2);
    sensitive << ( initPosition_reg_297 );

    SC_METHOD(thread_tmp_fu_171_p2);
    sensitive << ( y );

    SC_METHOD(thread_tmp_s_fu_209_p2);
    sensitive << ( initPosition_reg_297 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_7_fu_233_p2 );
    sensitive << ( tmp_8_fu_238_p2 );
    sensitive << ( tmp_12_fu_255_p2 );
    sensitive << ( tmp_13_fu_260_p2 );

    ap_CS_fsm = "000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "aStar_adjacentNodes_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x, "(port)x");
    sc_trace(mVcdFile, y, "(port)y");
    sc_trace(mVcdFile, adjacentPosition_2_address0, "(port)adjacentPosition_2_address0");
    sc_trace(mVcdFile, adjacentPosition_2_ce0, "(port)adjacentPosition_2_ce0");
    sc_trace(mVcdFile, adjacentPosition_2_we0, "(port)adjacentPosition_2_we0");
    sc_trace(mVcdFile, adjacentPosition_2_d0, "(port)adjacentPosition_2_d0");
    sc_trace(mVcdFile, adjacentPosition_2_address1, "(port)adjacentPosition_2_address1");
    sc_trace(mVcdFile, adjacentPosition_2_ce1, "(port)adjacentPosition_2_ce1");
    sc_trace(mVcdFile, adjacentPosition_2_we1, "(port)adjacentPosition_2_we1");
    sc_trace(mVcdFile, adjacentPosition_2_d1, "(port)adjacentPosition_2_d1");
    sc_trace(mVcdFile, adjacentPosition_0_address0, "(port)adjacentPosition_0_address0");
    sc_trace(mVcdFile, adjacentPosition_0_ce0, "(port)adjacentPosition_0_ce0");
    sc_trace(mVcdFile, adjacentPosition_0_we0, "(port)adjacentPosition_0_we0");
    sc_trace(mVcdFile, adjacentPosition_0_d0, "(port)adjacentPosition_0_d0");
    sc_trace(mVcdFile, adjacentPosition_0_address1, "(port)adjacentPosition_0_address1");
    sc_trace(mVcdFile, adjacentPosition_0_ce1, "(port)adjacentPosition_0_ce1");
    sc_trace(mVcdFile, adjacentPosition_0_we1, "(port)adjacentPosition_0_we1");
    sc_trace(mVcdFile, adjacentPosition_0_d1, "(port)adjacentPosition_0_d1");
    sc_trace(mVcdFile, adjacentPosition_1_address0, "(port)adjacentPosition_1_address0");
    sc_trace(mVcdFile, adjacentPosition_1_ce0, "(port)adjacentPosition_1_ce0");
    sc_trace(mVcdFile, adjacentPosition_1_we0, "(port)adjacentPosition_1_we0");
    sc_trace(mVcdFile, adjacentPosition_1_d0, "(port)adjacentPosition_1_d0");
    sc_trace(mVcdFile, adjacentPosition_1_address1, "(port)adjacentPosition_1_address1");
    sc_trace(mVcdFile, adjacentPosition_1_ce1, "(port)adjacentPosition_1_ce1");
    sc_trace(mVcdFile, adjacentPosition_1_we1, "(port)adjacentPosition_1_we1");
    sc_trace(mVcdFile, adjacentPosition_1_d1, "(port)adjacentPosition_1_d1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_36, "ap_sig_bdd_36");
    sc_trace(mVcdFile, initPosition_fu_177_p2, "initPosition_fu_177_p2");
    sc_trace(mVcdFile, initPosition_reg_297, "initPosition_reg_297");
    sc_trace(mVcdFile, tmp_7_fu_233_p2, "tmp_7_fu_233_p2");
    sc_trace(mVcdFile, tmp_7_reg_307, "tmp_7_reg_307");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_92, "ap_sig_bdd_92");
    sc_trace(mVcdFile, tmp_8_fu_238_p2, "tmp_8_fu_238_p2");
    sc_trace(mVcdFile, tmp_8_reg_311, "tmp_8_reg_311");
    sc_trace(mVcdFile, tmp_10_fu_243_p2, "tmp_10_fu_243_p2");
    sc_trace(mVcdFile, tmp_10_reg_315, "tmp_10_reg_315");
    sc_trace(mVcdFile, tmp_11_fu_249_p2, "tmp_11_fu_249_p2");
    sc_trace(mVcdFile, tmp_11_reg_320, "tmp_11_reg_320");
    sc_trace(mVcdFile, tmp_12_fu_255_p2, "tmp_12_fu_255_p2");
    sc_trace(mVcdFile, tmp_12_reg_325, "tmp_12_reg_325");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_113, "ap_sig_bdd_113");
    sc_trace(mVcdFile, tmp_13_fu_260_p2, "tmp_13_fu_260_p2");
    sc_trace(mVcdFile, tmp_13_reg_329, "tmp_13_reg_329");
    sc_trace(mVcdFile, tmp_14_fu_265_p2, "tmp_14_fu_265_p2");
    sc_trace(mVcdFile, tmp_14_reg_333, "tmp_14_reg_333");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_bdd_126, "ap_sig_bdd_126");
    sc_trace(mVcdFile, tmp_15_fu_271_p2, "tmp_15_fu_271_p2");
    sc_trace(mVcdFile, tmp_15_reg_339, "tmp_15_reg_339");
    sc_trace(mVcdFile, tmp_3_fu_183_p2, "tmp_3_fu_183_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_136, "ap_sig_bdd_136");
    sc_trace(mVcdFile, tmp_5_fu_197_p2, "tmp_5_fu_197_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_145, "ap_sig_bdd_145");
    sc_trace(mVcdFile, tmp_s_fu_209_p2, "tmp_s_fu_209_p2");
    sc_trace(mVcdFile, tmp_1_fu_221_p2, "tmp_1_fu_221_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_156, "ap_sig_bdd_156");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_165, "ap_sig_bdd_165");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_bdd_174, "ap_sig_bdd_174");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_bdd_183, "ap_sig_bdd_183");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st16_fsm_15, "ap_sig_cseq_ST_st16_fsm_15");
    sc_trace(mVcdFile, ap_sig_bdd_192, "ap_sig_bdd_192");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st18_fsm_17, "ap_sig_cseq_ST_st18_fsm_17");
    sc_trace(mVcdFile, ap_sig_bdd_201, "ap_sig_bdd_201");
    sc_trace(mVcdFile, tmp_4_fu_190_p2, "tmp_4_fu_190_p2");
    sc_trace(mVcdFile, tmp_6_fu_203_p2, "tmp_6_fu_203_p2");
    sc_trace(mVcdFile, tmp_9_fu_215_p2, "tmp_9_fu_215_p2");
    sc_trace(mVcdFile, tmp_2_fu_227_p2, "tmp_2_fu_227_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_bdd_225, "ap_sig_bdd_225");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_16, "ap_sig_cseq_ST_st17_fsm_16");
    sc_trace(mVcdFile, ap_sig_bdd_238, "ap_sig_bdd_238");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_260, "ap_sig_bdd_260");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_268, "ap_sig_bdd_268");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_bdd_324, "ap_sig_bdd_324");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_bdd_332, "ap_sig_bdd_332");
    sc_trace(mVcdFile, tmp_fu_171_p2, "tmp_fu_171_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

aStar_adjacentNodes::~aStar_adjacentNodes() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void aStar_adjacentNodes::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        initPosition_reg_297 = initPosition_fu_177_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_8_fu_238_p2.read(), ap_const_lv1_0))) {
        tmp_10_reg_315 = tmp_10_fu_243_p2.read();
        tmp_11_reg_320 = tmp_11_fu_249_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        tmp_12_reg_325 = tmp_12_fu_255_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()))) {
        tmp_13_reg_329 = tmp_13_fu_260_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        tmp_14_reg_333 = tmp_14_fu_265_p2.read();
        tmp_15_reg_339 = tmp_15_fu_271_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        tmp_7_reg_307 = tmp_7_fu_233_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0))) {
        tmp_8_reg_311 = tmp_8_fu_238_p2.read();
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        adjacentPosition_0_address0 = ap_const_lv3_6;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()))) {
        adjacentPosition_0_address0 = ap_const_lv3_7;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        adjacentPosition_0_address0 = ap_const_lv3_5;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()))) {
        adjacentPosition_0_address0 = ap_const_lv3_3;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                !esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0))) {
        adjacentPosition_0_address0 = ap_const_lv3_1;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                 esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_8_fu_238_p2.read(), ap_const_lv1_0)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                 esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0) && 
                 !esl_seteq<1,1,1>(tmp_8_fu_238_p2.read(), ap_const_lv1_0)))) {
        adjacentPosition_0_address0 = ap_const_lv3_0;
    } else {
        adjacentPosition_0_address0 = "XXX";
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_0_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        adjacentPosition_0_address1 = ap_const_lv3_5;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        adjacentPosition_0_address1 = ap_const_lv3_6;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        adjacentPosition_0_address1 = ap_const_lv3_4;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()))) {
        adjacentPosition_0_address1 = ap_const_lv3_2;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        adjacentPosition_0_address1 = ap_const_lv3_1;
    } else {
        adjacentPosition_0_address1 = "XXX";
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_0_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_8_fu_238_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0) && 
          !esl_seteq<1,1,1>(tmp_8_fu_238_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          !esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        adjacentPosition_0_ce0 = ap_const_logic_1;
    } else {
        adjacentPosition_0_ce0 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_0_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        adjacentPosition_0_ce1 = ap_const_logic_1;
    } else {
        adjacentPosition_0_ce1 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_0_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        adjacentPosition_0_d0 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        adjacentPosition_0_d0 = ap_const_lv32_3F;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        adjacentPosition_0_d0 = tmp_11_reg_320.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        adjacentPosition_0_d0 = x.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                 !esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0)))) {
        adjacentPosition_0_d0 = ap_const_lv32_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                 esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0) && 
                 !esl_seteq<1,1,1>(tmp_8_fu_238_p2.read(), ap_const_lv1_0)))) {
        adjacentPosition_0_d0 = ap_const_lv32_3E;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
                esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_8_fu_238_p2.read(), ap_const_lv1_0))) {
        adjacentPosition_0_d0 = tmp_10_fu_243_p2.read();
    } else {
        adjacentPosition_0_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_0_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        adjacentPosition_0_d1 = ap_const_lv32_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        adjacentPosition_0_d1 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        adjacentPosition_0_d1 = ap_const_lv32_3E;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        adjacentPosition_0_d1 = ap_const_lv32_3F;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        adjacentPosition_0_d1 = tmp_10_reg_315.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        adjacentPosition_0_d1 = x.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        adjacentPosition_0_d1 = tmp_11_fu_249_p2.read();
    } else {
        adjacentPosition_0_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_0_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_8_fu_238_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0) && 
          !esl_seteq<1,1,1>(tmp_8_fu_238_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          !esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          esl_seteq<1,1,1>(tmp_7_reg_307.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_8_reg_311.read(), ap_const_lv1_0)))) {
        adjacentPosition_0_we0 = ap_const_logic_1;
    } else {
        adjacentPosition_0_we0 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_0_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
          esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_8_fu_238_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          esl_seteq<1,1,1>(tmp_7_reg_307.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_8_reg_311.read(), ap_const_lv1_0)))) {
        adjacentPosition_0_we1 = ap_const_logic_1;
    } else {
        adjacentPosition_0_we1 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        adjacentPosition_1_address0 = ap_const_lv3_2;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        adjacentPosition_1_address0 = ap_const_lv3_7;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()))) {
        adjacentPosition_1_address0 = ap_const_lv3_5;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        adjacentPosition_1_address0 = ap_const_lv3_3;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_260_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_260_p2.read())) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read())))) {
        adjacentPosition_1_address0 = ap_const_lv3_0;
    } else {
        adjacentPosition_1_address0 = "XXX";
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_1_address1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        adjacentPosition_1_address1 = ap_const_lv3_6;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()))) {
        adjacentPosition_1_address1 = ap_const_lv3_4;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        adjacentPosition_1_address1 = ap_const_lv3_2;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        adjacentPosition_1_address1 = ap_const_lv3_1;
    } else {
        adjacentPosition_1_address1 = "XXX";
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_260_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_260_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        adjacentPosition_1_ce0 = ap_const_logic_1;
    } else {
        adjacentPosition_1_ce0 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_1_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        adjacentPosition_1_ce1 = ap_const_logic_1;
    } else {
        adjacentPosition_1_ce1 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_1_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        adjacentPosition_1_d0 = ap_const_lv32_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()))) {
        adjacentPosition_1_d0 = ap_const_lv32_22;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        adjacentPosition_1_d0 = tmp_15_reg_339.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        adjacentPosition_1_d0 = tmp_14_reg_333.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        adjacentPosition_1_d0 = tmp_15_fu_271_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()))) {
        adjacentPosition_1_d0 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_260_p2.read()))) {
        adjacentPosition_1_d0 = ap_const_lv32_23;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_260_p2.read()))) {
        adjacentPosition_1_d0 = y.read();
    } else {
        adjacentPosition_1_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_1_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        adjacentPosition_1_d1 = ap_const_lv32_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        adjacentPosition_1_d1 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        adjacentPosition_1_d1 = ap_const_lv32_22;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        adjacentPosition_1_d1 = ap_const_lv32_23;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        adjacentPosition_1_d1 = tmp_15_reg_339.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        adjacentPosition_1_d1 = tmp_14_reg_333.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        adjacentPosition_1_d1 = tmp_14_fu_265_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        adjacentPosition_1_d1 = y.read();
    } else {
        adjacentPosition_1_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_260_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_260_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_reg_325.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_reg_329.read())))) {
        adjacentPosition_1_we0 = ap_const_logic_1;
    } else {
        adjacentPosition_1_we0 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_1_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_260_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_reg_325.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_reg_329.read())))) {
        adjacentPosition_1_we1 = ap_const_logic_1;
    } else {
        adjacentPosition_1_we1 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_2_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        adjacentPosition_2_address0 = ap_const_lv3_3;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()))) {
        adjacentPosition_2_address0 = ap_const_lv3_7;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        adjacentPosition_2_address0 = ap_const_lv3_5;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        adjacentPosition_2_address0 = ap_const_lv3_2;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()))) {
        adjacentPosition_2_address0 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        adjacentPosition_2_address0 = ap_const_lv3_6;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()))) {
        adjacentPosition_2_address0 = ap_const_lv3_4;
    } else {
        adjacentPosition_2_address0 = "XXX";
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_2_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        adjacentPosition_2_address1 = ap_const_lv3_2;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()))) {
        adjacentPosition_2_address1 = ap_const_lv3_6;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        adjacentPosition_2_address1 = ap_const_lv3_4;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        adjacentPosition_2_address1 = ap_const_lv3_3;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()))) {
        adjacentPosition_2_address1 = ap_const_lv3_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        adjacentPosition_2_address1 = ap_const_lv3_7;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()))) {
        adjacentPosition_2_address1 = ap_const_lv3_5;
    } else {
        adjacentPosition_2_address1 = "XXX";
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_2_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()))) {
        adjacentPosition_2_ce0 = ap_const_logic_1;
    } else {
        adjacentPosition_2_ce0 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_2_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        adjacentPosition_2_ce1 = ap_const_logic_1;
    } else {
        adjacentPosition_2_ce1 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_2_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()))) {
        adjacentPosition_2_d0 = ap_const_lv32_FFFFFFFF;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        adjacentPosition_2_d0 = tmp_1_fu_221_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        adjacentPosition_2_d0 = tmp_s_fu_209_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        adjacentPosition_2_d0 = tmp_5_fu_197_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        adjacentPosition_2_d0 = tmp_3_fu_183_p2.read();
    } else {
        adjacentPosition_2_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_2_d1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        adjacentPosition_2_d1 = ap_const_lv32_FFFFFFFF;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        adjacentPosition_2_d1 = tmp_2_fu_227_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        adjacentPosition_2_d1 = tmp_9_fu_215_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        adjacentPosition_2_d1 = tmp_6_fu_203_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        adjacentPosition_2_d1 = tmp_4_fu_190_p2.read();
    } else {
        adjacentPosition_2_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_2_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()))) {
        adjacentPosition_2_we0 = ap_const_logic_1;
    } else {
        adjacentPosition_2_we0 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_adjacentPosition_2_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()))) {
        adjacentPosition_2_we1 = ap_const_logic_1;
    } else {
        adjacentPosition_2_we1 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_bdd_113() {
    ap_sig_bdd_113 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_126() {
    ap_sig_bdd_126 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_136() {
    ap_sig_bdd_136 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_145() {
    ap_sig_bdd_145 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_156() {
    ap_sig_bdd_156 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_165() {
    ap_sig_bdd_165 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_174() {
    ap_sig_bdd_174 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_183() {
    ap_sig_bdd_183 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_192() {
    ap_sig_bdd_192 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(15, 15));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_201() {
    ap_sig_bdd_201 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(17, 17));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_225() {
    ap_sig_bdd_225 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_238() {
    ap_sig_bdd_238 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(16, 16));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_260() {
    ap_sig_bdd_260 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_268() {
    ap_sig_bdd_268 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_324() {
    ap_sig_bdd_324 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_332() {
    ap_sig_bdd_332 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void aStar_adjacentNodes::thread_ap_sig_bdd_36() {
    ap_sig_bdd_36 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void aStar_adjacentNodes::thread_ap_sig_bdd_92() {
    ap_sig_bdd_92 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_bdd_225.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_bdd_174.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_bdd_126.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_bdd_324.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_bdd_332.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_bdd_183.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st16_fsm_15() {
    if (ap_sig_bdd_192.read()) {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st17_fsm_16() {
    if (ap_sig_bdd_238.read()) {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st18_fsm_17() {
    if (ap_sig_bdd_201.read()) {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_36.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_136.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_145.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_92.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_260.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_268.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_113.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_156.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_165.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void aStar_adjacentNodes::thread_initPosition_fu_177_p2() {
    initPosition_fu_177_p2 = (!x.read().is_01() || !tmp_fu_171_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(x.read()) + sc_biguint<32>(tmp_fu_171_p2.read()));
}

void aStar_adjacentNodes::thread_tmp_10_fu_243_p2() {
    tmp_10_fu_243_p2 = (!x.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(x.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void aStar_adjacentNodes::thread_tmp_11_fu_249_p2() {
    tmp_11_fu_249_p2 = (!x.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(x.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void aStar_adjacentNodes::thread_tmp_12_fu_255_p2() {
    tmp_12_fu_255_p2 = (!y.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(y.read() == ap_const_lv32_0);
}

void aStar_adjacentNodes::thread_tmp_13_fu_260_p2() {
    tmp_13_fu_260_p2 = (!y.read().is_01() || !ap_const_lv32_23.is_01())? sc_lv<1>(): sc_lv<1>(y.read() == ap_const_lv32_23);
}

void aStar_adjacentNodes::thread_tmp_14_fu_265_p2() {
    tmp_14_fu_265_p2 = (!y.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(y.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void aStar_adjacentNodes::thread_tmp_15_fu_271_p2() {
    tmp_15_fu_271_p2 = (!y.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(y.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void aStar_adjacentNodes::thread_tmp_1_fu_221_p2() {
    tmp_1_fu_221_p2 = (!ap_const_lv32_FFFFFFC0.is_01() || !initPosition_reg_297.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFC0) + sc_biguint<32>(initPosition_reg_297.read()));
}

void aStar_adjacentNodes::thread_tmp_2_fu_227_p2() {
    tmp_2_fu_227_p2 = (!ap_const_lv32_40.is_01() || !initPosition_reg_297.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_40) + sc_biguint<32>(initPosition_reg_297.read()));
}

void aStar_adjacentNodes::thread_tmp_3_fu_183_p2() {
    tmp_3_fu_183_p2 = (!ap_const_lv32_FFFFFFBF.is_01() || !initPosition_fu_177_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFBF) + sc_biguint<32>(initPosition_fu_177_p2.read()));
}

void aStar_adjacentNodes::thread_tmp_4_fu_190_p2() {
    tmp_4_fu_190_p2 = (!ap_const_lv32_FFFFFFC1.is_01() || !initPosition_fu_177_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFC1) + sc_biguint<32>(initPosition_fu_177_p2.read()));
}

void aStar_adjacentNodes::thread_tmp_5_fu_197_p2() {
    tmp_5_fu_197_p2 = (!ap_const_lv32_3F.is_01() || !initPosition_reg_297.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_3F) + sc_biguint<32>(initPosition_reg_297.read()));
}

void aStar_adjacentNodes::thread_tmp_6_fu_203_p2() {
    tmp_6_fu_203_p2 = (!ap_const_lv32_41.is_01() || !initPosition_reg_297.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_41) + sc_biguint<32>(initPosition_reg_297.read()));
}

void aStar_adjacentNodes::thread_tmp_7_fu_233_p2() {
    tmp_7_fu_233_p2 = (!x.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(x.read() == ap_const_lv32_0);
}

void aStar_adjacentNodes::thread_tmp_8_fu_238_p2() {
    tmp_8_fu_238_p2 = (!x.read().is_01() || !ap_const_lv32_3F.is_01())? sc_lv<1>(): sc_lv<1>(x.read() == ap_const_lv32_3F);
}

void aStar_adjacentNodes::thread_tmp_9_fu_215_p2() {
    tmp_9_fu_215_p2 = (!ap_const_lv32_1.is_01() || !initPosition_reg_297.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(initPosition_reg_297.read()));
}

void aStar_adjacentNodes::thread_tmp_fu_171_p2() {
    tmp_fu_171_p2 = (!ap_const_lv32_6.is_01())? sc_lv<32>(): y.read() << (unsigned short)ap_const_lv32_6.to_uint();
}

void aStar_adjacentNodes::thread_tmp_s_fu_209_p2() {
    tmp_s_fu_209_p2 = (!ap_const_lv32_FFFFFFFF.is_01() || !initPosition_reg_297.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFF) + sc_biguint<32>(initPosition_reg_297.read()));
}

void aStar_adjacentNodes::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(tmp_8_fu_238_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else if ((esl_seteq<1,1,1>(tmp_7_fu_233_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_8_fu_238_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_260_p2.read()))) {
                ap_NS_fsm = ap_ST_st15_fsm_14;
            } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_255_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_13_fu_260_p2.read()))) {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            } else {
                ap_NS_fsm = ap_ST_st17_fsm_16;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<18>) ("XXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

