#pragma line 1 "aStarStatic.cpp" ::: 0
#pragma line 1 "aStarStatic.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 145 "/home/jose/tfg/Vivado_HLS/2015.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 407 "/home/jose/tfg/Vivado_HLS/2015.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 198
#pragma line 6 "<command line>" 2 ::: 201
#pragma line 1 "<built-in>" 2 ::: 202
#pragma line 1 "aStarStatic.cpp" 2 ::: 203
#pragma line 1 "./aStarStatic.h" 1 ::: 211
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 215
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 243
#pragma line 128 "/usr/include/features.h" 3 4 ::: 344
#pragma line 149 "/usr/include/features.h" 3 4 ::: 358
#pragma line 177 "/usr/include/features.h" 3 4 ::: 360
#pragma line 193 "/usr/include/features.h" 3 4 ::: 363
#pragma line 350 "/usr/include/features.h" 3 4 ::: 394
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 398
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 433
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 439
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 462
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 503
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 509
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 527
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 533
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 537
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 539
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 543
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 553
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 606
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 647
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 668
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 692
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 693
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 695
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 697
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 698
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 723
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 734
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 739
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 740
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 741
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 748
#pragma line 56 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 784
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 787
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 789
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 817
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 819
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 821
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 882
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 889
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 907
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 912
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 923
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 992
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1006
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1009
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1010
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1042
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1058
#pragma line 56 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1083
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1086
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1091
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1113
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 1134
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1137
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1148
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1158
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1160
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1164
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1213
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1214
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1220
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1222
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1246
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1257
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1298
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1300
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1322
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1382
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1397
#pragma line 526 "/usr/include/libio.h" 3 4 ::: 1409
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1411
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1417
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1468
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1484
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1501
#pragma line 205 "/usr/include/stdio.h" 3 4 ::: 1533
#pragma line 297 "/usr/include/stdio.h" 3 4 ::: 1610
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1749
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1769
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2022
#pragma line 818 "/usr/include/stdio.h" 3 4 ::: 2033
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2070
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2102
#pragma line 931 "/usr/include/stdio.h" 3 4 ::: 2170
#pragma line 943 "/usr/include/stdio.h" 3 4 ::: 2173
#pragma line 5 "./aStarStatic.h" 2 ::: 2175
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2176
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2209
#pragma line 56 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2234
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2237
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2247
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2276
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2294
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2295
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2351
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2352
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2389
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2391
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2395
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2398
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2416
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2417
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2419
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2421
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2429
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2447
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2450
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2453
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2455
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2456
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2490
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2496
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2501
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2503
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2644
#pragma line 236 "/usr/include/stdlib.h" 2 3 4 ::: 2687
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2724
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2738
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2819
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2827
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2836
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2837
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2858
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2861
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2864
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2867
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2870
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2885
#pragma line 56 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2910
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2913
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2923
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2958
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2989
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3012
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3014
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3016
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3017
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3021
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3061
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3072
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3093
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3101
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 3103
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3138
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3225
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 3229
#pragma line 58 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3265
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3269
#pragma line 262 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3291
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3301
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3323
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3325
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3327
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3328
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3351
#pragma line 124 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3371
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3441
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3472
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3476
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3619
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3648
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3673
#pragma line 56 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3698
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3701
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3716
#pragma line 630 "/usr/include/stdlib.h" 3 4 ::: 3845
#pragma line 652 "/usr/include/stdlib.h" 3 4 ::: 3859
#pragma line 684 "/usr/include/stdlib.h" 3 4 ::: 3883
#pragma line 706 "/usr/include/stdlib.h" 3 4 ::: 3896
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4147
#pragma line 956 "/usr/include/stdlib.h" 2 3 4 ::: 4165
#pragma line 968 "/usr/include/stdlib.h" 3 4 ::: 4168
#pragma line 6 "./aStarStatic.h" 2 ::: 4170
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 4171
#pragma line 29 "/usr/include/time.h" 3 4 ::: 4192
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4202
#pragma line 56 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4227
#pragma line 38 "/usr/include/time.h" 2 3 4 ::: 4230
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 4235
#pragma line 42 "/usr/include/x86_64-linux-gnu/bits/time.h" 3 4 ::: 4257
#pragma line 60 "/usr/include/x86_64-linux-gnu/bits/time.h" 3 4 ::: 4264
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/timex.h" 1 3 4 ::: 4292
#pragma line 69 "/usr/include/x86_64-linux-gnu/bits/timex.h" 3 4 ::: 4348
#pragma line 83 "/usr/include/x86_64-linux-gnu/bits/timex.h" 3 4 ::: 4350
#pragma line 104 "/usr/include/x86_64-linux-gnu/bits/timex.h" 3 4 ::: 4352
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/time.h" 2 3 4 ::: 4354
#pragma line 42 "/usr/include/time.h" 2 3 4 ::: 4362
#pragma line 132 "/usr/include/time.h" 3 4 ::: 4365
#pragma line 181 "/usr/include/time.h" 3 4 ::: 4403
#pragma line 7 "./aStarStatic.h" 2 ::: 4654
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/iostream" 1 3 ::: 4655
#pragma line 37 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/iostream" 3 ::: 4693
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 1 3 ::: 4695
#pragma line 63 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 4738
#pragma line 76 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 4742
#pragma line 91 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 4746
#pragma line 102 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 4748
#pragma line 208 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 4815
#pragma line 255 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 4817
#pragma line 307 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 4828
#pragma line 326 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 4834
#pragma line 352 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 4836
#pragma line 390 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 3 ::: 4866
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/os_defines.h" 1 3 ::: 4871
#pragma line 394 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 2 3 ::: 4909
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/cpu_defines.h" 1 3 ::: 4913
#pragma line 397 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++config.h" 2 3 ::: 4942
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/iostream" 2 3 ::: 5793
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ostream" 1 3 ::: 5794
#pragma line 38 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ostream" 3 ::: 5833
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ios" 1 3 ::: 5835
#pragma line 37 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ios" 3 ::: 5873
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/iosfwd" 1 3 ::: 5875
#pragma line 38 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/iosfwd" 3 ::: 5914
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stringfwd.h" 1 3 ::: 5917
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stringfwd.h" 3 ::: 5957
#pragma line 82 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stringfwd.h" 3 ::: 5989
#pragma line 41 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/iosfwd" 2 3 ::: 5994
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/postypes.h" 1 3 ::: 5995
#pragma line 40 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/postypes.h" 3 ::: 6036
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwchar" 1 3 ::: 6038
#pragma line 41 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwchar" 3 ::: 6080
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 6085
#pragma line 31 "/usr/include/wchar.h" 3 4 ::: 6107
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 6119
#pragma line 42 "/usr/include/wchar.h" 2 3 4 ::: 6151
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 6162
#pragma line 56 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 6187
#pragma line 52 "/usr/include/wchar.h" 2 3 4 ::: 6194
#pragma line 63 "/usr/include/wchar.h" 3 4 ::: 6198
#pragma line 73 "/usr/include/wchar.h" 3 4 ::: 6201
#pragma line 99 "/usr/include/wchar.h" 3 4 ::: 6203
#pragma line 116 "/usr/include/wchar.h" 3 4 ::: 6212
#pragma line 125 "/usr/include/wchar.h" 3 4 ::: 6214
#pragma line 406 "/usr/include/wchar.h" 3 4 ::: 6468
#pragma line 685 "/usr/include/wchar.h" 3 4 ::: 6711
#pragma line 741 "/usr/include/wchar.h" 3 4 ::: 6732
#pragma line 891 "/usr/include/wchar.h" 3 4 ::: 6875
#pragma line 46 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwchar" 2 3 ::: 6884
#pragma line 63 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwchar" 3 ::: 6892
#pragma line 136 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwchar" 3 ::: 6899
#pragma line 258 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwchar" 3 ::: 7014
#pragma line 42 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/postypes.h" 2 3 ::: 7026
#pragma line 69 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/postypes.h" 3 ::: 7031
#pragma line 98 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/postypes.h" 3 ::: 7053
#pragma line 241 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/postypes.h" 3 ::: 7188
#pragma line 42 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/iosfwd" 2 3 ::: 7190
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ios" 2 3 ::: 7359
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/exception" 1 3 ::: 7360
#pragma line 35 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/exception" 3 ::: 7396
#pragma line 40 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ios" 2 3 ::: 7512
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/char_traits.h" 1 3 ::: 7513
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/char_traits.h" 3 ::: 7553
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 1 3 ::: 7555
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/functexcept.h" 1 3 ::: 7617
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/exception_defines.h" 1 3 ::: 7659
#pragma line 42 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/functexcept.h" 2 3 ::: 7696
#pragma line 62 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 2 3 ::: 7761
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 1 3 ::: 7762
#pragma line 36 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 7799
#pragma line 198 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 7944
#pragma line 422 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cpp_type_traits.h" 3 ::: 8155
#pragma line 63 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 2 3 ::: 8157
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/type_traits.h" 1 3 ::: 8158
#pragma line 33 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/type_traits.h" 3 ::: 8192
#pragma line 64 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 2 3 ::: 8372
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/numeric_traits.h" 1 3 ::: 8373
#pragma line 32 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/numeric_traits.h" 3 ::: 8406
#pragma line 53 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/numeric_traits.h" 3 ::: 8417
#pragma line 98 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/numeric_traits.h" 3 ::: 8442
#pragma line 65 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 2 3 ::: 8476
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_pair.h" 1 3 ::: 8477
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/move.h" 1 3 ::: 8538
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/concept_check.h" 1 3 ::: 8573
#pragma line 33 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/concept_check.h" 3 ::: 8607
#pragma line 35 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/move.h" 2 3 ::: 8618
#pragma line 109 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/move.h" 3 ::: 8635
#pragma line 61 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_pair.h" 2 3 ::: 8671
#pragma line 85 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_pair.h" 3 ::: 8679
#pragma line 196 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_pair.h" 3 ::: 8705
#pragma line 245 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_pair.h" 3 ::: 8744
#pragma line 270 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_pair.h" 3 ::: 8757
#pragma line 66 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 2 3 ::: 8766
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_iterator_base_types.h" 1 3 ::: 8767
#pragma line 63 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_iterator_base_types.h" 3 ::: 8831
#pragma line 162 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_iterator_base_types.h" 3 ::: 8909
#pragma line 67 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 2 3 ::: 8974
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_iterator_base_funcs.h" 1 3 ::: 8975
#pragma line 63 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_iterator_base_funcs.h" 3 ::: 9039
#pragma line 200 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_iterator_base_funcs.h" 3 ::: 9153
#pragma line 68 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 2 3 ::: 9155
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_iterator.h" 1 3 ::: 9156
#pragma line 68 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_iterator.h" 3 ::: 9216
#pragma line 444 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_iterator.h" 3 ::: 9577
#pragma line 534 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_iterator.h" 3 ::: 9652
#pragma line 648 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_iterator.h" 3 ::: 9749
#pragma line 69 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 2 3 ::: 10004
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/debug/debug.h" 1 3 ::: 10006
#pragma line 71 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 2 3 ::: 10065
#pragma line 135 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 3 ::: 10121
#pragma line 319 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 3 ::: 10290
#pragma line 357 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 3 ::: 10308
#pragma line 494 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 3 ::: 10408
#pragma line 522 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 3 ::: 10421
#pragma line 552 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 3 ::: 10435
#pragma line 669 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_algobase.h" 3 ::: 10511
#pragma line 41 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/char_traits.h" 2 3 ::: 11050
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwchar" 1 3 ::: 11052
#pragma line 41 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwchar" 3 ::: 11094
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 11099
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 11121
#pragma line 46 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwchar" 2 3 ::: 11124
#pragma line 43 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/char_traits.h" 2 3 ::: 11125
#pragma line 41 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ios" 2 3 ::: 11456
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/localefwd.h" 1 3 ::: 11457
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/localefwd.h" 3 ::: 11497
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++locale.h" 1 3 ::: 11500
#pragma line 40 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++locale.h" 3 ::: 11541
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/clocale" 1 3 ::: 11543
#pragma line 41 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/clocale" 3 ::: 11585
#pragma line 1 "/usr/include/locale.h" 1 3 4 ::: 11588
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 11617
#pragma line 56 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 11642
#pragma line 29 "/usr/include/locale.h" 2 3 4 ::: 11645
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/locale.h" 1 3 4 ::: 11646
#pragma line 30 "/usr/include/locale.h" 2 3 4 ::: 11664
#pragma line 52 "/usr/include/locale.h" 3 4 ::: 11670
#pragma line 120 "/usr/include/locale.h" 3 4 ::: 11731
#pragma line 184 "/usr/include/locale.h" 3 4 ::: 11770
#pragma line 44 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/clocale" 2 3 ::: 11793
#pragma line 42 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++locale.h" 2 3 ::: 11808
#pragma line 88 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++locale.h" 3 ::: 11843
#pragma line 42 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/localefwd.h" 2 3 ::: 11869
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cctype" 1 3 ::: 11871
#pragma line 41 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cctype" 3 ::: 11913
#pragma line 1 "/usr/include/ctype.h" 1 3 4 ::: 11916
#pragma line 46 "/usr/include/ctype.h" 3 4 ::: 11954
#pragma line 106 "/usr/include/ctype.h" 3 4 ::: 11994
#pragma line 244 "/usr/include/ctype.h" 3 4 ::: 12052
#pragma line 347 "/usr/include/ctype.h" 3 4 ::: 12102
#pragma line 44 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cctype" 2 3 ::: 12104
#pragma line 63 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cctype" 3 ::: 12110
#pragma line 44 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/localefwd.h" 2 3 ::: 12127
#pragma line 42 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ios" 2 3 ::: 12274
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/ios_base.h" 1 3 ::: 12275
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/ios_base.h" 3 ::: 12315
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/atomicity.h" 1 3 ::: 12317
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr.h" 1 3 ::: 12352
#pragma line 158 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr.h" 3 ::: 12496
#pragma line 170 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr.h" 3 ::: 12500
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr-default.h" 1 3 ::: 12501
#pragma line 1 "/usr/include/pthread.h" 1 3 4 ::: 12543
#pragma line 1 "/usr/include/sched.h" 1 3 4 ::: 12567
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 12596
#pragma line 56 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 12621
#pragma line 29 "/usr/include/sched.h" 2 3 4 ::: 12624
#pragma line 40 "/usr/include/sched.h" 3 4 ::: 12625
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sched.h" 1 3 4 ::: 12628
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/sched.h" 3 4 ::: 12647
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/sched.h" 3 4 ::: 12649
#pragma line 71 "/usr/include/x86_64-linux-gnu/bits/sched.h" 3 4 ::: 12651
#pragma line 201 "/usr/include/x86_64-linux-gnu/bits/sched.h" 3 4 ::: 12712
#pragma line 42 "/usr/include/sched.h" 2 3 4 ::: 12721
#pragma line 115 "/usr/include/sched.h" 3 4 ::: 12757
#pragma line 24 "/usr/include/pthread.h" 2 3 4 ::: 12768
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/setjmp.h" 1 3 4 ::: 12772
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 12799
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 12801
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/setjmp.h" 2 3 4 ::: 12803
#pragma line 28 "/usr/include/pthread.h" 2 3 4 ::: 12809
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 12810
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 12812
#pragma line 29 "/usr/include/pthread.h" 2 3 4 ::: 12814
#pragma line 123 "/usr/include/pthread.h" 3 4 ::: 12872
#pragma line 165 "/usr/include/pthread.h" 3 4 ::: 12893
#pragma line 668 "/usr/include/pthread.h" 3 4 ::: 13287
#pragma line 691 "/usr/include/pthread.h" 3 4 ::: 13295
#pragma line 726 "/usr/include/pthread.h" 3 4 ::: 13315
#pragma line 1170 "/usr/include/pthread.h" 3 4 ::: 13749
#pragma line 42 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr-default.h" 2 3 ::: 13751
#pragma line 1 "/usr/include/unistd.h" 1 3 4 ::: 13752
#pragma line 49 "/usr/include/unistd.h" 3 4 ::: 13786
#pragma line 66 "/usr/include/unistd.h" 3 4 ::: 13793
#pragma line 96 "/usr/include/unistd.h" 3 4 ::: 13814
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/posix_opt.h" 1 3 4 ::: 13922
#pragma line 203 "/usr/include/unistd.h" 2 3 4 ::: 14111
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/environments.h" 1 3 4 ::: 14116
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 14139
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 14141
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/environments.h" 2 3 4 ::: 14143
#pragma line 207 "/usr/include/unistd.h" 2 3 4 ::: 14182
#pragma line 226 "/usr/include/unistd.h" 3 4 ::: 14192
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 14193
#pragma line 56 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 14218
#pragma line 227 "/usr/include/unistd.h" 2 3 4 ::: 14221
#pragma line 267 "/usr/include/unistd.h" 3 4 ::: 14226
#pragma line 321 "/usr/include/unistd.h" 3 4 ::: 14270
#pragma line 345 "/usr/include/unistd.h" 3 4 ::: 14285
#pragma line 401 "/usr/include/unistd.h" 3 4 ::: 14327
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/confname.h" 1 3 4 ::: 14537
#pragma line 610 "/usr/include/unistd.h" 2 3 4 ::: 15213
#pragma line 1 "/usr/include/getopt.h" 1 3 4 ::: 15476
#pragma line 48 "/usr/include/getopt.h" 3 4 ::: 15508
#pragma line 122 "/usr/include/getopt.h" 3 4 ::: 15542
#pragma line 185 "/usr/include/getopt.h" 3 4 ::: 15573
#pragma line 872 "/usr/include/unistd.h" 2 3 4 ::: 15578
#pragma line 1005 "/usr/include/unistd.h" 3 4 ::: 15702
#pragma line 1026 "/usr/include/unistd.h" 3 4 ::: 15715
#pragma line 1035 "/usr/include/unistd.h" 3 4 ::: 15717
#pragma line 1091 "/usr/include/unistd.h" 3 4 ::: 15765
#pragma line 1110 "/usr/include/unistd.h" 3 4 ::: 15775
#pragma line 43 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr-default.h" 2 3 ::: 15818
#pragma line 81 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr-default.h" 3 ::: 15830
#pragma line 118 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr-default.h" 3 ::: 15837
#pragma line 183 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr-default.h" 3 ::: 15875
#pragma line 239 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr-default.h" 3 ::: 15886
#pragma line 657 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr-default.h" 3 ::: 15900
#pragma line 800 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr-default.h" 3 ::: 16020
#pragma line 171 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/gthr.h" 2 3 ::: 16095
#pragma line 35 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/atomicity.h" 2 3 ::: 16104
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/atomic_word.h" 1 3 ::: 16105
#pragma line 36 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/atomicity.h" 2 3 ::: 16151
#pragma line 63 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/atomicity.h" 3 ::: 16169
#pragma line 41 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/ios_base.h" 2 3 ::: 16216
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_classes.h" 1 3 ::: 16218
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_classes.h" 3 ::: 16258
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/string" 1 3 ::: 16261
#pragma line 38 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/string" 3 ::: 16300
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/allocator.h" 1 3 ::: 16305
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++allocator.h" 1 3 ::: 16354
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/new_allocator.h" 1 3 ::: 16389
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/new" 1 3 ::: 16424
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/new" 3 ::: 16464
#pragma line 35 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/new_allocator.h" 2 3 ::: 16538
#pragma line 117 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ext/new_allocator.h" 3 ::: 16613
#pragma line 35 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/c++allocator.h" 2 3 ::: 16630
#pragma line 49 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/allocator.h" 2 3 ::: 16631
#pragma line 237 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/allocator.h" 3 ::: 16766
#pragma line 43 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/string" 2 3 ::: 16768
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/ostream_insert.h" 1 3 ::: 16771
#pragma line 33 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/ostream_insert.h" 3 ::: 16805
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cxxabi_forced.h" 1 3 ::: 16808
#pragma line 34 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/cxxabi_forced.h" 3 ::: 16843
#pragma line 36 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/ostream_insert.h" 2 3 ::: 16868
#pragma line 46 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/string" 2 3 ::: 16960
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_function.h" 1 3 ::: 16964
#pragma line 508 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_function.h" 3 ::: 17460
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/backward/binders.h" 1 3 ::: 17685
#pragma line 732 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/stl_function.h" 2 3 ::: 17856
#pragma line 50 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/string" 2 3 ::: 17857
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/range_access.h" 1 3 ::: 17860
#pragma line 33 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/range_access.h" 3 ::: 17894
#pragma line 53 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/string" 2 3 ::: 17895
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 1 3 ::: 17896
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 17936
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/initializer_list" 1 3 ::: 17940
#pragma line 33 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/initializer_list" 3 ::: 17974
#pragma line 43 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 2 3 ::: 17975
#pragma line 519 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 18425
#pragma line 593 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 18471
#pragma line 704 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 18546
#pragma line 762 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 18592
#pragma line 896 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 18692
#pragma line 958 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 18743
#pragma line 1024 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 18798
#pragma line 1076 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 18833
#pragma line 1160 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 18906
#pragma line 1207 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 18938
#pragma line 1663 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 19375
#pragma line 2417 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.h" 3 ::: 20079
#pragma line 54 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/string" 2 3 ::: 20414
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.tcc" 1 3 ::: 20415
#pragma line 42 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.tcc" 3 ::: 20458
#pragma line 241 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_string.tcc" 3 ::: 20649
#pragma line 55 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/string" 2 3 ::: 21575
#pragma line 42 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_classes.h" 2 3 ::: 21576
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_classes.tcc" 1 3 ::: 22358
#pragma line 37 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_classes.tcc" 3 ::: 22396
#pragma line 823 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_classes.h" 2 3 ::: 22631
#pragma line 43 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/ios_base.h" 2 3 ::: 22632
#pragma line 43 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ios" 2 3 ::: 23565
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/streambuf" 1 3 ::: 23566
#pragma line 37 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/streambuf" 3 ::: 23604
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/streambuf.tcc" 1 3 ::: 24376
#pragma line 38 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/streambuf.tcc" 3 ::: 24415
#pragma line 808 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/streambuf" 2 3 ::: 24552
#pragma line 44 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ios" 2 3 ::: 24553
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_ios.h" 1 3 ::: 24554
#pragma line 35 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_ios.h" 3 ::: 24590
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.h" 1 3 ::: 24594
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.h" 3 ::: 24634
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwctype" 1 3 ::: 24636
#pragma line 41 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwctype" 3 ::: 24678
#pragma line 51 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwctype" 3 ::: 24679
#pragma line 1 "/usr/include/wctype.h" 1 3 4 ::: 24680
#pragma line 31 "/usr/include/wctype.h" 3 4 ::: 24702
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 24706
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 24728
#pragma line 34 "/usr/include/wctype.h" 2 3 4 ::: 24731
#pragma line 71 "/usr/include/wctype.h" 3 4 ::: 24757
#pragma line 52 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwctype" 2 3 ::: 25002
#pragma line 81 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cwctype" 3 ::: 25009
#pragma line 41 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.h" 2 3 ::: 25037
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cctype" 1 3 ::: 25038
#pragma line 41 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/cctype" 3 ::: 25080
#pragma line 42 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.h" 2 3 ::: 25081
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/ctype_base.h" 1 3 ::: 25082
#pragma line 43 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.h" 2 3 ::: 25147
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/streambuf_iterator.h" 1 3 ::: 25154
#pragma line 35 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/streambuf_iterator.h" 3 ::: 25190
#pragma line 50 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.h" 2 3 ::: 25556
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/x86_64-unknown-linux-gnu/bits/ctype_inline.h" 1 3 ::: 27019
#pragma line 1512 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.h" 2 3 ::: 27096
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.tcc" 1 3 ::: 28193
#pragma line 35 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.tcc" 3 ::: 28229
#pragma line 731 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.tcc" 3 ::: 28908
#pragma line 1026 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.tcc" 3 ::: 29185
#pragma line 1153 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.tcc" 3 ::: 29304
#pragma line 2608 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/locale_facets.h" 2 3 ::: 29512
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_ios.h" 2 3 ::: 29513
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_ios.tcc" 1 3 ::: 29948
#pragma line 34 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_ios.tcc" 3 ::: 29983
#pragma line 473 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/basic_ios.h" 2 3 ::: 30137
#pragma line 45 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ios" 2 3 ::: 30138
#pragma line 40 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ostream" 2 3 ::: 30139
#pragma line 585 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ostream" 3 ::: 30665
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/ostream.tcc" 1 3 ::: 30669
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/ostream.tcc" 3 ::: 30709
#pragma line 588 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/ostream" 2 3 ::: 31078
#pragma line 40 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/iostream" 2 3 ::: 31079
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/istream" 1 3 ::: 31080
#pragma line 38 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/istream" 3 ::: 31119
#pragma line 856 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/istream" 3 ::: 31918
#pragma line 1 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/istream.tcc" 1 3 ::: 31922
#pragma line 39 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/bits/istream.tcc" 3 ::: 31962
#pragma line 859 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/istream" 2 3 ::: 33016
#pragma line 41 "/home/jose/tfg/Vivado_HLS/2015.4/lnx64/tools/gcc/lib/gcc/x86_64-unknown-linux-gnu/4.6.3/../../../../include/c++/4.6.3/iostream" 2 3 ::: 33017
#pragma line 8 "./aStarStatic.h" 2 ::: 33055
#pragma line 8 "aStarStatic.cpp" 2 ::: 33087
