// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="aStar,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.480000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=50,HLS_SYN_DSP=0,HLS_SYN_FF=1276,HLS_SYN_LUT=2438}" *)

module aStar (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        xStart,
        yStart,
        xFinish,
        yFinish,
        map_r_address0,
        map_r_ce0,
        map_r_we0,
        map_r_d0,
        map_r_q0,
        ap_return
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 32'b1;
parameter    ap_ST_st2_fsm_1 = 32'b10;
parameter    ap_ST_st3_fsm_2 = 32'b100;
parameter    ap_ST_st4_fsm_3 = 32'b1000;
parameter    ap_ST_st5_fsm_4 = 32'b10000;
parameter    ap_ST_st6_fsm_5 = 32'b100000;
parameter    ap_ST_st7_fsm_6 = 32'b1000000;
parameter    ap_ST_st8_fsm_7 = 32'b10000000;
parameter    ap_ST_st9_fsm_8 = 32'b100000000;
parameter    ap_ST_st10_fsm_9 = 32'b1000000000;
parameter    ap_ST_st11_fsm_10 = 32'b10000000000;
parameter    ap_ST_st12_fsm_11 = 32'b100000000000;
parameter    ap_ST_st13_fsm_12 = 32'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 32'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 32'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 32'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 32'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 32'b100000000000000000;
parameter    ap_ST_st19_fsm_18 = 32'b1000000000000000000;
parameter    ap_ST_st20_fsm_19 = 32'b10000000000000000000;
parameter    ap_ST_st21_fsm_20 = 32'b100000000000000000000;
parameter    ap_ST_st22_fsm_21 = 32'b1000000000000000000000;
parameter    ap_ST_st23_fsm_22 = 32'b10000000000000000000000;
parameter    ap_ST_st24_fsm_23 = 32'b100000000000000000000000;
parameter    ap_ST_st25_fsm_24 = 32'b1000000000000000000000000;
parameter    ap_ST_st26_fsm_25 = 32'b10000000000000000000000000;
parameter    ap_ST_st27_fsm_26 = 32'b100000000000000000000000000;
parameter    ap_ST_st28_fsm_27 = 32'b1000000000000000000000000000;
parameter    ap_ST_st29_fsm_28 = 32'b10000000000000000000000000000;
parameter    ap_ST_st30_fsm_29 = 32'b100000000000000000000000000000;
parameter    ap_ST_st31_fsm_30 = 32'b1000000000000000000000000000000;
parameter    ap_ST_st32_fsm_31 = 32'b10000000000000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_1A = 32'b11010;
parameter    ap_const_lv32_1B = 32'b11011;
parameter    ap_const_lv32_1C = 32'b11100;
parameter    ap_const_lv32_1D = 32'b11101;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_7FFFFFFF = 32'b1111111111111111111111111111111;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_19 = 32'b11001;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv12_900 = 12'b100100000000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] xStart;
input  [31:0] yStart;
input  [31:0] xFinish;
input  [31:0] yFinish;
output  [11:0] map_r_address0;
output   map_r_ce0;
output   map_r_we0;
output  [31:0] map_r_d0;
input  [31:0] map_r_q0;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[11:0] map_r_address0;
reg map_r_ce0;
reg map_r_we0;
reg[31:0] map_r_d0;
(* fsm_encoding = "none" *) reg   [31:0] ap_CS_fsm = 32'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_48;
reg   [11:0] openNodes_address0;
reg    openNodes_ce0;
reg    openNodes_we0;
reg   [0:0] openNodes_d0;
wire   [0:0] openNodes_q0;
reg   [11:0] node_coordinates_0_address0;
reg    node_coordinates_0_ce0;
reg    node_coordinates_0_we0;
wire   [5:0] node_coordinates_0_d0;
wire   [5:0] node_coordinates_0_q0;
reg   [11:0] node_coordinates_1_address0;
reg    node_coordinates_1_ce0;
reg    node_coordinates_1_we0;
wire   [31:0] node_coordinates_1_d0;
wire   [31:0] node_coordinates_1_q0;
reg   [11:0] node_visited_address0;
reg    node_visited_ce0;
reg    node_visited_we0;
reg   [0:0] node_visited_d0;
wire   [0:0] node_visited_q0;
reg   [11:0] node_father_address0;
reg    node_father_ce0;
reg    node_father_we0;
reg   [31:0] node_father_d0;
wire   [31:0] node_father_q0;
reg   [11:0] node_cost_address0;
reg    node_cost_ce0;
reg    node_cost_we0;
reg   [31:0] node_cost_d0;
wire   [31:0] node_cost_q0;
reg   [11:0] node_heuristic_address0;
reg    node_heuristic_ce0;
reg    node_heuristic_we0;
reg   [31:0] node_heuristic_d0;
reg   [11:0] node_costPlusHeuristic_address0;
reg    node_costPlusHeuristic_ce0;
reg    node_costPlusHeuristic_we0;
reg   [31:0] node_costPlusHeuristic_d0;
wire   [31:0] node_costPlusHeuristic_q0;
reg   [2:0] adjacentPosition_2_address0;
reg    adjacentPosition_2_ce0;
reg    adjacentPosition_2_we0;
wire   [31:0] adjacentPosition_2_d0;
wire   [31:0] adjacentPosition_2_q0;
wire   [2:0] adjacentPosition_2_address1;
reg    adjacentPosition_2_ce1;
reg    adjacentPosition_2_we1;
wire   [31:0] adjacentPosition_2_d1;
reg   [2:0] adjacentPosition_0_address0;
reg    adjacentPosition_0_ce0;
reg    adjacentPosition_0_we0;
wire   [31:0] adjacentPosition_0_d0;
wire   [31:0] adjacentPosition_0_q0;
wire   [2:0] adjacentPosition_0_address1;
reg    adjacentPosition_0_ce1;
reg    adjacentPosition_0_we1;
wire   [31:0] adjacentPosition_0_d1;
reg   [2:0] adjacentPosition_1_address0;
reg    adjacentPosition_1_ce0;
reg    adjacentPosition_1_we0;
wire   [31:0] adjacentPosition_1_d0;
wire   [31:0] adjacentPosition_1_q0;
wire   [2:0] adjacentPosition_1_address1;
reg    adjacentPosition_1_ce1;
reg    adjacentPosition_1_we1;
wire   [31:0] adjacentPosition_1_d1;
reg   [31:0] reg_718;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_189;
reg    ap_sig_cseq_ST_st20_fsm_19;
reg    ap_sig_bdd_196;
wire   [31:0] grp_fu_708_p2;
reg   [31:0] reg_723;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_bdd_206;
reg    ap_sig_cseq_ST_st22_fsm_21;
reg    ap_sig_bdd_213;
wire   [31:0] grp_fu_713_p2;
reg   [31:0] reg_727;
wire   [5:0] x_fu_783_p1;
reg   [5:0] x_reg_1304;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_236;
wire   [11:0] i_1_fu_793_p2;
reg   [11:0] i_1_reg_1314;
wire   [0:0] or_cond_i_fu_811_p2;
reg   [0:0] or_cond_i_reg_1319;
wire   [0:0] exitcond_i_fu_787_p2;
wire   [31:0] position_5_fu_822_p2;
reg   [31:0] position_5_reg_1324;
wire   [31:0] y_1_fu_833_p3;
reg   [31:0] y_1_reg_1330;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_257;
wire   [3:0] i_2_fu_916_p2;
reg   [3:0] i_2_reg_1347;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_268;
wire   [63:0] tmp_17_fu_922_p1;
reg   [63:0] tmp_17_reg_1352;
wire   [0:0] exitcond1_fu_910_p2;
wire  signed [63:0] tmp_18_fu_927_p1;
reg  signed [63:0] tmp_18_reg_1363;
wire   [0:0] grp_fu_737_p2;
reg   [0:0] or_cond_reg_1377;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_bdd_288;
wire   [31:0] tmp_i1_fu_932_p2;
reg   [31:0] tmp_i1_reg_1391;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_bdd_303;
wire    grp_aStar_calculateCost_fu_696_ap_done;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_bdd_316;
wire   [31:0] positionBestOption_i_cast_fu_961_p1;
reg   [31:0] positionBestOption_i_cast_reg_1403;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_bdd_325;
wire   [11:0] i_4_fu_971_p2;
reg   [11:0] i_4_reg_1411;
wire   [0:0] exitcond_i1_fu_965_p2;
wire   [31:0] finalPosition_fu_994_p2;
reg   [31:0] finalPosition_reg_1426;
wire   [31:0] positionBestOption_2_i_fu_1020_p3;
reg    ap_sig_cseq_ST_st14_fsm_13;
reg    ap_sig_bdd_347;
wire   [31:0] bestOption_2_i_fu_1028_p3;
reg   [11:0] node_coordinates_0_addr_1_reg_1442;
reg    ap_sig_cseq_ST_st15_fsm_14;
reg    ap_sig_bdd_358;
reg   [11:0] node_coordinates_1_addr_reg_1447;
reg   [5:0] node_coordinates_0_load_reg_1452;
reg    ap_sig_cseq_ST_st16_fsm_15;
reg    ap_sig_bdd_368;
reg   [31:0] node_coordinates_1_load_reg_1457;
wire   [31:0] extLd_fu_1042_p1;
reg   [31:0] extLd_reg_1462;
reg    ap_sig_cseq_ST_st17_fsm_16;
reg    ap_sig_bdd_378;
wire   [3:0] i_3_fu_1052_p2;
reg   [3:0] i_3_reg_1470;
reg    ap_sig_cseq_ST_st19_fsm_18;
reg    ap_sig_bdd_387;
wire   [63:0] tmp_21_fu_1058_p1;
reg   [63:0] tmp_21_reg_1475;
wire   [0:0] exitcond_fu_1046_p2;
wire  signed [63:0] tmp_23_fu_1063_p1;
reg  signed [63:0] tmp_23_reg_1486;
reg   [0:0] or_cond1_reg_1500;
reg    ap_sig_cseq_ST_st21_fsm_20;
reg    ap_sig_bdd_406;
wire   [31:0] tmp_i5_fu_1081_p2;
reg   [31:0] tmp_i5_reg_1514;
reg    ap_sig_cseq_ST_st23_fsm_22;
reg    ap_sig_bdd_420;
reg    ap_sig_cseq_ST_st25_fsm_24;
reg    ap_sig_bdd_429;
wire   [31:0] positionBestOption_i11_cast_fu_1110_p1;
reg   [31:0] positionBestOption_i11_cast_reg_1526;
reg    ap_sig_cseq_ST_st27_fsm_26;
reg    ap_sig_bdd_438;
wire   [11:0] i_5_fu_1120_p2;
reg   [11:0] i_5_reg_1534;
wire   [0:0] exitcond_i2_fu_1114_p2;
wire   [31:0] positionBestOption_2_i1_fu_1164_p3;
reg    ap_sig_cseq_ST_st28_fsm_27;
reg    ap_sig_bdd_456;
wire   [31:0] bestOption_2_i1_fu_1172_p3;
wire  signed [63:0] tmp_25_fu_1180_p1;
reg  signed [63:0] tmp_25_reg_1562;
reg    ap_sig_cseq_ST_st29_fsm_28;
reg    ap_sig_bdd_467;
reg   [31:0] position_reg_1573;
reg    ap_sig_cseq_ST_st30_fsm_29;
reg    ap_sig_bdd_477;
wire   [0:0] tmp_26_fu_1185_p2;
wire   [12:0] tmp_33_fu_1267_p2;
reg   [12:0] tmp_33_reg_1591;
reg    ap_sig_cseq_ST_st31_fsm_30;
reg    ap_sig_bdd_493;
wire    grp_aStar_adjacentNodes_fu_684_ap_start;
wire    grp_aStar_adjacentNodes_fu_684_ap_done;
wire    grp_aStar_adjacentNodes_fu_684_ap_idle;
wire    grp_aStar_adjacentNodes_fu_684_ap_ready;
reg   [31:0] grp_aStar_adjacentNodes_fu_684_x;
reg   [31:0] grp_aStar_adjacentNodes_fu_684_y;
wire   [2:0] grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_address0;
wire    grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_ce0;
wire    grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_we0;
wire   [31:0] grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_d0;
wire   [2:0] grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_address1;
wire    grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_ce1;
wire    grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_we1;
wire   [31:0] grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_d1;
wire   [2:0] grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_address0;
wire    grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_ce0;
wire    grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_we0;
wire   [31:0] grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_d0;
wire   [2:0] grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_address1;
wire    grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_ce1;
wire    grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_we1;
wire   [31:0] grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_d1;
wire   [2:0] grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_address0;
wire    grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_ce0;
wire    grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_we0;
wire   [31:0] grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_d0;
wire   [2:0] grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_address1;
wire    grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_ce1;
wire    grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_we1;
wire   [31:0] grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_d1;
wire    grp_aStar_calculateCost_fu_696_ap_start;
wire    grp_aStar_calculateCost_fu_696_ap_idle;
wire    grp_aStar_calculateCost_fu_696_ap_ready;
reg   [3:0] grp_aStar_calculateCost_fu_696_i;
wire   [31:0] grp_aStar_calculateCost_fu_696_position;
wire   [11:0] grp_aStar_calculateCost_fu_696_node_father_address0;
wire    grp_aStar_calculateCost_fu_696_node_father_ce0;
wire   [31:0] grp_aStar_calculateCost_fu_696_node_father_q0;
wire   [11:0] grp_aStar_calculateCost_fu_696_node_cost_address0;
wire    grp_aStar_calculateCost_fu_696_node_cost_ce0;
wire    grp_aStar_calculateCost_fu_696_node_cost_we0;
wire   [31:0] grp_aStar_calculateCost_fu_696_node_cost_d0;
wire   [31:0] grp_aStar_calculateCost_fu_696_node_cost_q0;
reg   [31:0] y_i_reg_546;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_549;
reg   [11:0] i_i_reg_558;
reg   [3:0] i_reg_570;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_562;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_572;
reg   [11:0] positionBestOption_reg_582;
reg   [31:0] position_3_reg_593;
reg   [31:0] bestOption_i_reg_605;
reg   [31:0] position3_reg_617;
wire   [0:0] tmp_22_fu_1138_p2;
reg   [3:0] i1_reg_627;
reg    ap_sig_cseq_ST_st18_fsm_17;
reg    ap_sig_bdd_598;
reg    ap_sig_cseq_ST_st26_fsm_25;
reg    ap_sig_bdd_606;
reg   [11:0] positionBestOption_1_reg_639;
reg   [31:0] position_4_reg_650;
reg   [31:0] bestOption_i1_reg_663;
reg   [31:0] position_1_reg_675;
reg    ap_sig_cseq_ST_st32_fsm_31;
reg    ap_sig_bdd_622;
reg    grp_aStar_adjacentNodes_fu_684_ap_start_ap_start_reg = 1'b0;
reg    grp_aStar_calculateCost_fu_696_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st24_fsm_23;
reg    ap_sig_bdd_639;
wire  signed [63:0] tmp_35_cast_fu_882_p1;
wire   [63:0] tmp_2_i_fu_887_p1;
wire   [0:0] tmp_9_i_fu_896_p2;
wire   [11:0] node_visited_addr_1_gep_fu_198_p3;
wire  signed [63:0] tmp_s_fu_902_p1;
wire   [63:0] tmp_i7_fu_977_p1;
wire  signed [63:0] tmp_i_fu_983_p1;
wire  signed [63:0] tmp_20_fu_1036_p1;
wire   [63:0] tmp_i8_fu_1126_p1;
wire  signed [63:0] tmp_i3_fu_1132_p1;
wire  signed [63:0] tmp_45_cast_fu_1228_p1;
wire  signed [63:0] tmp_49_cast_fu_1273_p1;
wire   [31:0] positionFather_1_fu_1072_p3;
wire   [31:0] tmp_1_i_fu_954_p2;
wire   [31:0] tmp_1_i1_fu_1103_p2;
wire   [0:0] grp_fu_731_p2;
wire   [0:0] grp_fu_749_p2;
wire   [31:0] grp_fu_743_p2;
wire   [0:0] grp_fu_769_p2;
wire   [31:0] grp_fu_763_p2;
wire   [0:0] tmp_4_i_fu_799_p2;
wire   [0:0] tmp_5_i_fu_805_p2;
wire   [31:0] tmp_1_fu_817_p2;
wire   [31:0] y_fu_827_p2;
wire   [10:0] tmp_16_fu_844_p3;
wire   [7:0] tmp_27_fu_855_p3;
wire   [11:0] p_shl_cast_fu_851_p1;
wire   [11:0] p_shl1_cast_fu_862_p1;
wire   [11:0] tmp_28_fu_866_p2;
wire   [12:0] tmp_fu_840_p1;
wire   [12:0] tmp_34_cast_fu_872_p1;
wire   [12:0] tmp_29_fu_876_p2;
wire   [31:0] grp_fu_775_p3;
wire   [31:0] grp_fu_755_p3;
wire   [31:0] tmp_3_fu_938_p2;
wire   [31:0] tmp_4_fu_943_p2;
wire   [31:0] tmp1_fu_948_p2;
wire   [31:0] tmp_2_fu_989_p2;
wire   [0:0] tmp_8_i9_fu_999_p2;
wire   [31:0] positionBestOption_positionBes_fu_1005_p3;
wire   [31:0] bestOption_1_bestOption_i_fu_1012_p3;
wire   [25:0] tmp_5_fu_1068_p1;
wire   [31:0] tmp_7_fu_1092_p2;
wire   [31:0] tmp_6_fu_1087_p2;
wire   [31:0] tmp2_fu_1097_p2;
wire   [0:0] tmp_8_i1_fu_1143_p2;
wire   [31:0] positionBestOption_positionBes_1_fu_1149_p3;
wire   [31:0] bestOption_1_bestOption_i1_fu_1156_p3;
wire   [7:0] tmp_9_fu_1194_p1;
wire   [10:0] tmp_10_fu_1205_p1;
wire   [12:0] p_shl4_cast_fu_1197_p3;
wire   [12:0] p_shl5_cast_fu_1208_p3;
wire   [12:0] tmp_8_fu_1191_p1;
wire   [12:0] tmp_30_fu_1216_p2;
wire   [12:0] tmp_31_fu_1222_p2;
wire   [10:0] tmp_12_fu_1237_p3;
wire   [7:0] tmp_13_fu_1249_p3;
wire   [12:0] p_shl3_cast_fu_1257_p1;
wire   [12:0] p_shl2_cast_fu_1245_p1;
wire   [12:0] tmp_32_fu_1261_p2;
wire   [12:0] tmp_11_fu_1233_p1;
reg   [31:0] ap_NS_fsm;


aStar_openNodes #(
    .DataWidth( 1 ),
    .AddressRange( 2304 ),
    .AddressWidth( 12 ))
openNodes_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( openNodes_address0 ),
    .ce0( openNodes_ce0 ),
    .we0( openNodes_we0 ),
    .d0( openNodes_d0 ),
    .q0( openNodes_q0 )
);

aStar_node_coordinates_0 #(
    .DataWidth( 6 ),
    .AddressRange( 2304 ),
    .AddressWidth( 12 ))
node_coordinates_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( node_coordinates_0_address0 ),
    .ce0( node_coordinates_0_ce0 ),
    .we0( node_coordinates_0_we0 ),
    .d0( node_coordinates_0_d0 ),
    .q0( node_coordinates_0_q0 )
);

aStar_node_coordinates_1 #(
    .DataWidth( 32 ),
    .AddressRange( 2304 ),
    .AddressWidth( 12 ))
node_coordinates_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( node_coordinates_1_address0 ),
    .ce0( node_coordinates_1_ce0 ),
    .we0( node_coordinates_1_we0 ),
    .d0( node_coordinates_1_d0 ),
    .q0( node_coordinates_1_q0 )
);

aStar_openNodes #(
    .DataWidth( 1 ),
    .AddressRange( 2304 ),
    .AddressWidth( 12 ))
node_visited_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( node_visited_address0 ),
    .ce0( node_visited_ce0 ),
    .we0( node_visited_we0 ),
    .d0( node_visited_d0 ),
    .q0( node_visited_q0 )
);

aStar_node_coordinates_1 #(
    .DataWidth( 32 ),
    .AddressRange( 2304 ),
    .AddressWidth( 12 ))
node_father_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( node_father_address0 ),
    .ce0( node_father_ce0 ),
    .we0( node_father_we0 ),
    .d0( node_father_d0 ),
    .q0( node_father_q0 )
);

aStar_node_coordinates_1 #(
    .DataWidth( 32 ),
    .AddressRange( 2304 ),
    .AddressWidth( 12 ))
node_cost_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( node_cost_address0 ),
    .ce0( node_cost_ce0 ),
    .we0( node_cost_we0 ),
    .d0( node_cost_d0 ),
    .q0( node_cost_q0 )
);

aStar_node_heuristic #(
    .DataWidth( 32 ),
    .AddressRange( 2304 ),
    .AddressWidth( 12 ))
node_heuristic_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( node_heuristic_address0 ),
    .ce0( node_heuristic_ce0 ),
    .we0( node_heuristic_we0 ),
    .d0( node_heuristic_d0 )
);

aStar_node_coordinates_1 #(
    .DataWidth( 32 ),
    .AddressRange( 2304 ),
    .AddressWidth( 12 ))
node_costPlusHeuristic_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( node_costPlusHeuristic_address0 ),
    .ce0( node_costPlusHeuristic_ce0 ),
    .we0( node_costPlusHeuristic_we0 ),
    .d0( node_costPlusHeuristic_d0 ),
    .q0( node_costPlusHeuristic_q0 )
);

aStar_adjacentPosition_2 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
adjacentPosition_2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( adjacentPosition_2_address0 ),
    .ce0( adjacentPosition_2_ce0 ),
    .we0( adjacentPosition_2_we0 ),
    .d0( adjacentPosition_2_d0 ),
    .q0( adjacentPosition_2_q0 ),
    .address1( adjacentPosition_2_address1 ),
    .ce1( adjacentPosition_2_ce1 ),
    .we1( adjacentPosition_2_we1 ),
    .d1( adjacentPosition_2_d1 )
);

aStar_adjacentPosition_2 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
adjacentPosition_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( adjacentPosition_0_address0 ),
    .ce0( adjacentPosition_0_ce0 ),
    .we0( adjacentPosition_0_we0 ),
    .d0( adjacentPosition_0_d0 ),
    .q0( adjacentPosition_0_q0 ),
    .address1( adjacentPosition_0_address1 ),
    .ce1( adjacentPosition_0_ce1 ),
    .we1( adjacentPosition_0_we1 ),
    .d1( adjacentPosition_0_d1 )
);

aStar_adjacentPosition_2 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
adjacentPosition_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( adjacentPosition_1_address0 ),
    .ce0( adjacentPosition_1_ce0 ),
    .we0( adjacentPosition_1_we0 ),
    .d0( adjacentPosition_1_d0 ),
    .q0( adjacentPosition_1_q0 ),
    .address1( adjacentPosition_1_address1 ),
    .ce1( adjacentPosition_1_ce1 ),
    .we1( adjacentPosition_1_we1 ),
    .d1( adjacentPosition_1_d1 )
);

aStar_adjacentNodes grp_aStar_adjacentNodes_fu_684(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_aStar_adjacentNodes_fu_684_ap_start ),
    .ap_done( grp_aStar_adjacentNodes_fu_684_ap_done ),
    .ap_idle( grp_aStar_adjacentNodes_fu_684_ap_idle ),
    .ap_ready( grp_aStar_adjacentNodes_fu_684_ap_ready ),
    .x( grp_aStar_adjacentNodes_fu_684_x ),
    .y( grp_aStar_adjacentNodes_fu_684_y ),
    .adjacentPosition_2_address0( grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_address0 ),
    .adjacentPosition_2_ce0( grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_ce0 ),
    .adjacentPosition_2_we0( grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_we0 ),
    .adjacentPosition_2_d0( grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_d0 ),
    .adjacentPosition_2_address1( grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_address1 ),
    .adjacentPosition_2_ce1( grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_ce1 ),
    .adjacentPosition_2_we1( grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_we1 ),
    .adjacentPosition_2_d1( grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_d1 ),
    .adjacentPosition_0_address0( grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_address0 ),
    .adjacentPosition_0_ce0( grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_ce0 ),
    .adjacentPosition_0_we0( grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_we0 ),
    .adjacentPosition_0_d0( grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_d0 ),
    .adjacentPosition_0_address1( grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_address1 ),
    .adjacentPosition_0_ce1( grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_ce1 ),
    .adjacentPosition_0_we1( grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_we1 ),
    .adjacentPosition_0_d1( grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_d1 ),
    .adjacentPosition_1_address0( grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_address0 ),
    .adjacentPosition_1_ce0( grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_ce0 ),
    .adjacentPosition_1_we0( grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_we0 ),
    .adjacentPosition_1_d0( grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_d0 ),
    .adjacentPosition_1_address1( grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_address1 ),
    .adjacentPosition_1_ce1( grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_ce1 ),
    .adjacentPosition_1_we1( grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_we1 ),
    .adjacentPosition_1_d1( grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_d1 )
);

aStar_calculateCost grp_aStar_calculateCost_fu_696(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_aStar_calculateCost_fu_696_ap_start ),
    .ap_done( grp_aStar_calculateCost_fu_696_ap_done ),
    .ap_idle( grp_aStar_calculateCost_fu_696_ap_idle ),
    .ap_ready( grp_aStar_calculateCost_fu_696_ap_ready ),
    .i( grp_aStar_calculateCost_fu_696_i ),
    .position( grp_aStar_calculateCost_fu_696_position ),
    .node_father_address0( grp_aStar_calculateCost_fu_696_node_father_address0 ),
    .node_father_ce0( grp_aStar_calculateCost_fu_696_node_father_ce0 ),
    .node_father_q0( grp_aStar_calculateCost_fu_696_node_father_q0 ),
    .node_cost_address0( grp_aStar_calculateCost_fu_696_node_cost_address0 ),
    .node_cost_ce0( grp_aStar_calculateCost_fu_696_node_cost_ce0 ),
    .node_cost_we0( grp_aStar_calculateCost_fu_696_node_cost_we0 ),
    .node_cost_d0( grp_aStar_calculateCost_fu_696_node_cost_d0 ),
    .node_cost_q0( grp_aStar_calculateCost_fu_696_node_cost_q0 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_aStar_adjacentNodes_fu_684_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_aStar_adjacentNodes_fu_684_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond_i_fu_787_p2 == ap_const_lv1_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16))) begin
            grp_aStar_adjacentNodes_fu_684_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_aStar_adjacentNodes_fu_684_ap_ready)) begin
            grp_aStar_adjacentNodes_fu_684_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_grp_aStar_calculateCost_fu_696_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_aStar_calculateCost_fu_696_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st23_fsm_22))) begin
            grp_aStar_calculateCost_fu_696_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_aStar_calculateCost_fu_696_ap_ready)) begin
            grp_aStar_calculateCost_fu_696_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) & ~(ap_const_lv1_0 == exitcond_fu_1046_p2))) begin
        bestOption_i1_reg_663 <= ap_const_lv32_7FFFFFFF;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27)) begin
        bestOption_i1_reg_663 <= bestOption_2_i1_fu_1172_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) & ~(ap_const_lv1_0 == exitcond1_fu_910_p2))) begin
        bestOption_i_reg_605 <= ap_const_lv32_7FFFFFFF;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        bestOption_i_reg_605 <= bestOption_2_i_fu_1028_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25)) begin
        i1_reg_627 <= i_3_reg_1470;
    end else if ((~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done) & (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        i1_reg_627 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        i_i_reg_558 <= i_1_reg_1314;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        i_i_reg_558 <= ap_const_lv12_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        i_reg_570 <= i_2_reg_1347;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done))) begin
        i_reg_570 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & (ap_const_lv1_0 == tmp_22_fu_1138_p2) & ~(ap_const_lv1_0 == exitcond_i2_fu_1114_p2))) begin
        position3_reg_617 <= position_4_reg_650;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~(ap_const_lv1_0 == exitcond_i1_fu_965_p2))) begin
        position3_reg_617 <= position_3_reg_593;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) & ~(ap_const_lv1_0 == exitcond_fu_1046_p2))) begin
        positionBestOption_1_reg_639 <= ap_const_lv12_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27)) begin
        positionBestOption_1_reg_639 <= i_5_reg_1534;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) & ~(ap_const_lv1_0 == exitcond1_fu_910_p2))) begin
        positionBestOption_reg_582 <= ap_const_lv12_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        positionBestOption_reg_582 <= i_4_reg_1411;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & ~(ap_const_lv1_0 == exitcond_i2_fu_1114_p2) & ~(ap_const_lv1_0 == tmp_22_fu_1138_p2))) begin
        position_1_reg_675 <= finalPosition_reg_1426;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st32_fsm_31)) begin
        position_1_reg_675 <= position_reg_1573;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        y_i_reg_546 <= y_1_reg_1330;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        y_i_reg_546 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        extLd_reg_1462[5 : 0] <= extLd_fu_1042_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~(ap_const_lv1_0 == exitcond_i1_fu_965_p2))) begin
        finalPosition_reg_1426 <= finalPosition_fu_994_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        i_1_reg_1314 <= i_1_fu_793_p2;
        x_reg_1304 <= x_fu_783_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        i_2_reg_1347 <= i_2_fu_916_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18)) begin
        i_3_reg_1470 <= i_3_fu_1052_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        i_4_reg_1411 <= i_4_fu_971_p2;
        positionBestOption_i_cast_reg_1403[11 : 0] <= positionBestOption_i_cast_fu_961_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26)) begin
        i_5_reg_1534 <= i_5_fu_1120_p2;
        positionBestOption_i11_cast_reg_1526[11 : 0] <= positionBestOption_i11_cast_fu_1110_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        node_coordinates_0_addr_1_reg_1442 <= tmp_20_fu_1036_p1;
        node_coordinates_1_addr_reg_1447 <= tmp_20_fu_1036_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15)) begin
        node_coordinates_0_load_reg_1452 <= node_coordinates_0_q0;
        node_coordinates_1_load_reg_1457 <= node_coordinates_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20)) begin
        or_cond1_reg_1500 <= grp_fu_737_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond_i_fu_787_p2 == ap_const_lv1_0))) begin
        or_cond_i_reg_1319 <= or_cond_i_fu_811_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        or_cond_reg_1377 <= grp_fu_737_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        position_3_reg_593 <= positionBestOption_2_i_fu_1020_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st28_fsm_27)) begin
        position_4_reg_650 <= positionBestOption_2_i1_fu_1164_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond_i_fu_787_p2 == ap_const_lv1_0))) begin
        position_5_reg_1324 <= position_5_fu_822_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st30_fsm_29)) begin
        position_reg_1573 <= node_father_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19))) begin
        reg_718 <= adjacentPosition_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st22_fsm_21))) begin
        reg_723 <= grp_fu_708_p2;
        reg_727 <= grp_fu_713_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) & (ap_const_lv1_0 == exitcond1_fu_910_p2))) begin
        tmp_17_reg_1352[3 : 0] <= tmp_17_fu_922_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        tmp_18_reg_1363 <= tmp_18_fu_927_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) & (ap_const_lv1_0 == exitcond_fu_1046_p2))) begin
        tmp_21_reg_1475[3 : 0] <= tmp_21_fu_1058_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        tmp_23_reg_1486 <= tmp_23_fu_1063_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st29_fsm_28)) begin
        tmp_25_reg_1562 <= tmp_25_fu_1180_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st31_fsm_30)) begin
        tmp_33_reg_1591 <= tmp_33_fu_1267_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & ~(ap_const_logic_0 == grp_aStar_calculateCost_fu_696_ap_done))) begin
        tmp_i1_reg_1391 <= tmp_i1_fu_932_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st23_fsm_22)) begin
        tmp_i5_reg_1514 <= tmp_i5_fu_1081_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        y_1_reg_1330 <= y_1_fu_833_p3;
    end
end

always @ (tmp_17_reg_1352 or ap_sig_cseq_ST_st8_fsm_7 or tmp_21_reg_1475 or ap_sig_cseq_ST_st21_fsm_20 or grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_address0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20)) begin
        adjacentPosition_0_address0 = tmp_21_reg_1475;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        adjacentPosition_0_address0 = tmp_17_reg_1352;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_0_address0 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_address0;
    end else begin
        adjacentPosition_0_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st21_fsm_20 or grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_ce0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20))) begin
        adjacentPosition_0_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_0_ce0 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_ce0;
    end else begin
        adjacentPosition_0_ce0 = ap_const_logic_0;
    end
end

always @ (grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_ce1 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_0_ce1 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_ce1;
    end else begin
        adjacentPosition_0_ce1 = ap_const_logic_0;
    end
end

always @ (grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_we0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_0_we0 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_we0;
    end else begin
        adjacentPosition_0_we0 = ap_const_logic_0;
    end
end

always @ (grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_we1 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_0_we1 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_we1;
    end else begin
        adjacentPosition_0_we1 = ap_const_logic_0;
    end
end

always @ (tmp_17_reg_1352 or ap_sig_cseq_ST_st8_fsm_7 or tmp_21_reg_1475 or ap_sig_cseq_ST_st21_fsm_20 or grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_address0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20)) begin
        adjacentPosition_1_address0 = tmp_21_reg_1475;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        adjacentPosition_1_address0 = tmp_17_reg_1352;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_1_address0 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_address0;
    end else begin
        adjacentPosition_1_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st21_fsm_20 or grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_ce0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20))) begin
        adjacentPosition_1_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_1_ce0 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_ce0;
    end else begin
        adjacentPosition_1_ce0 = ap_const_logic_0;
    end
end

always @ (grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_ce1 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_1_ce1 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_ce1;
    end else begin
        adjacentPosition_1_ce1 = ap_const_logic_0;
    end
end

always @ (grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_we0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_1_we0 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_we0;
    end else begin
        adjacentPosition_1_we0 = ap_const_logic_0;
    end
end

always @ (grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_we1 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_1_we1 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_we1;
    end else begin
        adjacentPosition_1_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st6_fsm_5 or tmp_17_fu_922_p1 or ap_sig_cseq_ST_st19_fsm_18 or tmp_21_fu_1058_p1 or grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_address0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18)) begin
        adjacentPosition_2_address0 = tmp_21_fu_1058_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        adjacentPosition_2_address0 = tmp_17_fu_922_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_2_address0 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_address0;
    end else begin
        adjacentPosition_2_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st19_fsm_18 or grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_ce0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | (ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18))) begin
        adjacentPosition_2_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_2_ce0 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_ce0;
    end else begin
        adjacentPosition_2_ce0 = ap_const_logic_0;
    end
end

always @ (grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_ce1 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_2_ce1 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_ce1;
    end else begin
        adjacentPosition_2_ce1 = ap_const_logic_0;
    end
end

always @ (grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_we0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_2_we0 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_we0;
    end else begin
        adjacentPosition_2_we0 = ap_const_logic_0;
    end
end

always @ (grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_we1 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_2_we1 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_we1;
    end else begin
        adjacentPosition_2_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st30_fsm_29 or tmp_26_fu_1185_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st30_fsm_29) & ~(ap_const_lv1_0 == tmp_26_fu_1185_p2))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st30_fsm_29 or tmp_26_fu_1185_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st30_fsm_29) & ~(ap_const_lv1_0 == tmp_26_fu_1185_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_303) begin
    if (ap_sig_bdd_303) begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_316) begin
    if (ap_sig_bdd_316) begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_572) begin
    if (ap_sig_bdd_572) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_325) begin
    if (ap_sig_bdd_325) begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_347) begin
    if (ap_sig_bdd_347) begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_358) begin
    if (ap_sig_bdd_358) begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_368) begin
    if (ap_sig_bdd_368) begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_378) begin
    if (ap_sig_bdd_378) begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_598) begin
    if (ap_sig_bdd_598) begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_387) begin
    if (ap_sig_bdd_387) begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_48) begin
    if (ap_sig_bdd_48) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_196) begin
    if (ap_sig_bdd_196) begin
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_406) begin
    if (ap_sig_bdd_406) begin
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_213) begin
    if (ap_sig_bdd_213) begin
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_420) begin
    if (ap_sig_bdd_420) begin
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_639) begin
    if (ap_sig_bdd_639) begin
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_429) begin
    if (ap_sig_bdd_429) begin
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_606) begin
    if (ap_sig_bdd_606) begin
        ap_sig_cseq_ST_st26_fsm_25 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st26_fsm_25 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_438) begin
    if (ap_sig_bdd_438) begin
        ap_sig_cseq_ST_st27_fsm_26 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st27_fsm_26 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_456) begin
    if (ap_sig_bdd_456) begin
        ap_sig_cseq_ST_st28_fsm_27 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st28_fsm_27 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_467) begin
    if (ap_sig_bdd_467) begin
        ap_sig_cseq_ST_st29_fsm_28 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st29_fsm_28 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_236) begin
    if (ap_sig_bdd_236) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_477) begin
    if (ap_sig_bdd_477) begin
        ap_sig_cseq_ST_st30_fsm_29 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st30_fsm_29 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_493) begin
    if (ap_sig_bdd_493) begin
        ap_sig_cseq_ST_st31_fsm_30 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st31_fsm_30 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_622) begin
    if (ap_sig_bdd_622) begin
        ap_sig_cseq_ST_st32_fsm_31 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st32_fsm_31 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_257) begin
    if (ap_sig_bdd_257) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_549) begin
    if (ap_sig_bdd_549) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_562) begin
    if (ap_sig_bdd_562) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_268) begin
    if (ap_sig_bdd_268) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_189) begin
    if (ap_sig_bdd_189) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_288) begin
    if (ap_sig_bdd_288) begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_206) begin
    if (ap_sig_bdd_206) begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    end
end

always @ (xStart or extLd_reg_1462 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17)) begin
        grp_aStar_adjacentNodes_fu_684_x = extLd_reg_1462;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        grp_aStar_adjacentNodes_fu_684_x = xStart;
    end else begin
        grp_aStar_adjacentNodes_fu_684_x = 'bx;
    end
end

always @ (yStart or node_coordinates_1_load_reg_1457 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st18_fsm_17) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17)) begin
        grp_aStar_adjacentNodes_fu_684_y = node_coordinates_1_load_reg_1457;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        grp_aStar_adjacentNodes_fu_684_y = yStart;
    end else begin
        grp_aStar_adjacentNodes_fu_684_y = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st10_fsm_9 or i_reg_570 or i1_reg_627 or ap_sig_cseq_ST_st24_fsm_23) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st24_fsm_23)) begin
        grp_aStar_calculateCost_fu_696_i = i1_reg_627;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        grp_aStar_calculateCost_fu_696_i = i_reg_570;
    end else begin
        grp_aStar_calculateCost_fu_696_i = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st30_fsm_29 or ap_sig_cseq_ST_st32_fsm_31 or tmp_35_cast_fu_882_p1 or tmp_45_cast_fu_1228_p1 or tmp_49_cast_fu_1273_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st32_fsm_31)) begin
        map_r_address0 = tmp_49_cast_fu_1273_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st30_fsm_29)) begin
        map_r_address0 = tmp_45_cast_fu_1228_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        map_r_address0 = tmp_35_cast_fu_882_p1;
    end else begin
        map_r_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st30_fsm_29 or ap_sig_cseq_ST_st32_fsm_31) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) | (ap_const_logic_1 == ap_sig_cseq_ST_st30_fsm_29) | (ap_const_logic_1 == ap_sig_cseq_ST_st32_fsm_31))) begin
        map_r_ce0 = ap_const_logic_1;
    end else begin
        map_r_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st30_fsm_29 or ap_sig_cseq_ST_st32_fsm_31) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st32_fsm_31)) begin
        map_r_d0 = ap_const_lv32_2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st30_fsm_29)) begin
        map_r_d0 = ap_const_lv32_4;
    end else begin
        map_r_d0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st30_fsm_29 or tmp_26_fu_1185_p2 or ap_sig_cseq_ST_st32_fsm_31) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st32_fsm_31) | ((ap_const_logic_1 == ap_sig_cseq_ST_st30_fsm_29) & ~(ap_const_lv1_0 == tmp_26_fu_1185_p2)))) begin
        map_r_we0 = ap_const_logic_1;
    end else begin
        map_r_we0 = ap_const_logic_0;
    end
end

always @ (node_coordinates_0_addr_1_reg_1442 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st21_fsm_20 or tmp_25_reg_1562 or ap_sig_cseq_ST_st30_fsm_29 or ap_sig_cseq_ST_st4_fsm_3 or tmp_2_i_fu_887_p1 or tmp_20_fu_1036_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        node_coordinates_0_address0 = tmp_2_i_fu_887_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st30_fsm_29)) begin
        node_coordinates_0_address0 = tmp_25_reg_1562;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20)) begin
        node_coordinates_0_address0 = node_coordinates_0_addr_1_reg_1442;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        node_coordinates_0_address0 = tmp_20_fu_1036_p1;
    end else begin
        node_coordinates_0_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st21_fsm_20 or ap_sig_cseq_ST_st30_fsm_29 or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20) | (ap_const_logic_1 == ap_sig_cseq_ST_st30_fsm_29) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3))) begin
        node_coordinates_0_ce0 = ap_const_logic_1;
    end else begin
        node_coordinates_0_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st4_fsm_3 or tmp_9_i_fu_896_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == tmp_9_i_fu_896_p2))) begin
        node_coordinates_0_we0 = ap_const_logic_1;
    end else begin
        node_coordinates_0_we0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st15_fsm_14 or node_coordinates_1_addr_reg_1447 or ap_sig_cseq_ST_st21_fsm_20 or tmp_25_reg_1562 or ap_sig_cseq_ST_st30_fsm_29 or ap_sig_cseq_ST_st4_fsm_3 or tmp_2_i_fu_887_p1 or tmp_20_fu_1036_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        node_coordinates_1_address0 = tmp_2_i_fu_887_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st30_fsm_29)) begin
        node_coordinates_1_address0 = tmp_25_reg_1562;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20)) begin
        node_coordinates_1_address0 = node_coordinates_1_addr_reg_1447;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        node_coordinates_1_address0 = tmp_20_fu_1036_p1;
    end else begin
        node_coordinates_1_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st21_fsm_20 or ap_sig_cseq_ST_st30_fsm_29 or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20) | (ap_const_logic_1 == ap_sig_cseq_ST_st30_fsm_29) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3))) begin
        node_coordinates_1_ce0 = ap_const_logic_1;
    end else begin
        node_coordinates_1_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st4_fsm_3 or tmp_9_i_fu_896_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == tmp_9_i_fu_896_p2))) begin
        node_coordinates_1_we0 = ap_const_logic_1;
    end else begin
        node_coordinates_1_we0 = ap_const_logic_0;
    end
end

always @ (tmp_18_reg_1363 or ap_sig_cseq_ST_st13_fsm_12 or tmp_23_reg_1486 or ap_sig_cseq_ST_st27_fsm_26 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st26_fsm_25 or tmp_s_fu_902_p1 or tmp_i7_fu_977_p1 or tmp_i8_fu_1126_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25)) begin
        node_costPlusHeuristic_address0 = tmp_23_reg_1486;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        node_costPlusHeuristic_address0 = tmp_18_reg_1363;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        node_costPlusHeuristic_address0 = tmp_s_fu_902_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26)) begin
        node_costPlusHeuristic_address0 = tmp_i8_fu_1126_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        node_costPlusHeuristic_address0 = tmp_i7_fu_977_p1;
    end else begin
        node_costPlusHeuristic_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st27_fsm_26 or grp_aStar_adjacentNodes_fu_684_ap_done or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st26_fsm_25) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) | ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done)) | (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25))) begin
        node_costPlusHeuristic_ce0 = ap_const_logic_1;
    end else begin
        node_costPlusHeuristic_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st26_fsm_25 or tmp_1_i_fu_954_p2 or tmp_1_i1_fu_1103_p2) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25)) begin
        node_costPlusHeuristic_d0 = tmp_1_i1_fu_1103_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        node_costPlusHeuristic_d0 = tmp_1_i_fu_954_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        node_costPlusHeuristic_d0 = ap_const_lv32_0;
    end else begin
        node_costPlusHeuristic_d0 = 'bx;
    end
end

always @ (or_cond_reg_1377 or or_cond1_reg_1500 or grp_aStar_adjacentNodes_fu_684_ap_done or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st26_fsm_25) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) & (ap_const_lv1_0 == or_cond_reg_1377)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25) & (ap_const_lv1_0 == or_cond1_reg_1500)))) begin
        node_costPlusHeuristic_we0 = ap_const_logic_1;
    end else begin
        node_costPlusHeuristic_we0 = ap_const_logic_0;
    end
end

always @ (tmp_18_reg_1363 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st11_fsm_10 or tmp_23_reg_1486 or ap_sig_cseq_ST_st25_fsm_24 or grp_aStar_calculateCost_fu_696_node_cost_address0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st24_fsm_23 or tmp_s_fu_902_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        node_cost_address0 = tmp_s_fu_902_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st25_fsm_24)) begin
        node_cost_address0 = tmp_23_reg_1486;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        node_cost_address0 = tmp_18_reg_1363;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st24_fsm_23))) begin
        node_cost_address0 = grp_aStar_calculateCost_fu_696_node_cost_address0;
    end else begin
        node_cost_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st25_fsm_24 or grp_aStar_adjacentNodes_fu_684_ap_done or grp_aStar_calculateCost_fu_696_node_cost_ce0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st24_fsm_23) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st25_fsm_24) | ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done)))) begin
        node_cost_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st24_fsm_23))) begin
        node_cost_ce0 = grp_aStar_calculateCost_fu_696_node_cost_ce0;
    end else begin
        node_cost_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st10_fsm_9 or grp_aStar_calculateCost_fu_696_node_cost_d0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st24_fsm_23) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        node_cost_d0 = ap_const_lv32_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st24_fsm_23))) begin
        node_cost_d0 = grp_aStar_calculateCost_fu_696_node_cost_d0;
    end else begin
        node_cost_d0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st10_fsm_9 or grp_aStar_adjacentNodes_fu_684_ap_done or grp_aStar_calculateCost_fu_696_node_cost_we0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st24_fsm_23) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done))) begin
        node_cost_we0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st24_fsm_23))) begin
        node_cost_we0 = grp_aStar_calculateCost_fu_696_node_cost_we0;
    end else begin
        node_cost_we0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st22_fsm_21 or tmp_18_reg_1363 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st10_fsm_9 or tmp_23_reg_1486 or tmp_25_fu_1180_p1 or ap_sig_cseq_ST_st29_fsm_28 or grp_aStar_calculateCost_fu_696_node_father_address0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st24_fsm_23 or tmp_s_fu_902_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st22_fsm_21)) begin
        node_father_address0 = tmp_23_reg_1486;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        node_father_address0 = tmp_18_reg_1363;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        node_father_address0 = tmp_s_fu_902_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st29_fsm_28)) begin
        node_father_address0 = tmp_25_fu_1180_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st24_fsm_23))) begin
        node_father_address0 = grp_aStar_calculateCost_fu_696_node_father_address0;
    end else begin
        node_father_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st22_fsm_21 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st29_fsm_28 or grp_aStar_adjacentNodes_fu_684_ap_done or grp_aStar_calculateCost_fu_696_node_father_ce0 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st24_fsm_23) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st22_fsm_21) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st29_fsm_28) | ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done)))) begin
        node_father_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st24_fsm_23))) begin
        node_father_ce0 = grp_aStar_calculateCost_fu_696_node_father_ce0;
    end else begin
        node_father_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st22_fsm_21 or position_5_reg_1324 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st5_fsm_4 or positionFather_1_fu_1072_p3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st22_fsm_21)) begin
        node_father_d0 = positionFather_1_fu_1072_p3;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        node_father_d0 = position_5_reg_1324;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        node_father_d0 = ap_const_lv32_FFFFFFFF;
    end else begin
        node_father_d0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st22_fsm_21 or grp_fu_737_p2 or ap_sig_cseq_ST_st8_fsm_7 or grp_aStar_adjacentNodes_fu_684_ap_done or ap_sig_cseq_ST_st5_fsm_4) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st22_fsm_21) | ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (ap_const_lv1_0 == grp_fu_737_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done)))) begin
        node_father_we0 = ap_const_logic_1;
    end else begin
        node_father_we0 = ap_const_logic_0;
    end
end

always @ (tmp_18_reg_1363 or tmp_23_reg_1486 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st26_fsm_25 or tmp_s_fu_902_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25)) begin
        node_heuristic_address0 = tmp_23_reg_1486;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        node_heuristic_address0 = tmp_18_reg_1363;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        node_heuristic_address0 = tmp_s_fu_902_p1;
    end else begin
        node_heuristic_address0 = 'bx;
    end
end

always @ (grp_aStar_adjacentNodes_fu_684_ap_done or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st26_fsm_25) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done)) | (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25))) begin
        node_heuristic_ce0 = ap_const_logic_1;
    end else begin
        node_heuristic_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_i1_reg_1391 or tmp_i5_reg_1514 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st26_fsm_25) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25)) begin
        node_heuristic_d0 = tmp_i5_reg_1514;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        node_heuristic_d0 = tmp_i1_reg_1391;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        node_heuristic_d0 = ap_const_lv32_0;
    end else begin
        node_heuristic_d0 = 'bx;
    end
end

always @ (or_cond_reg_1377 or or_cond1_reg_1500 or grp_aStar_adjacentNodes_fu_684_ap_done or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st26_fsm_25) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) & (ap_const_lv1_0 == or_cond_reg_1377)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25) & (ap_const_lv1_0 == or_cond1_reg_1500)))) begin
        node_heuristic_we0 = ap_const_logic_1;
    end else begin
        node_heuristic_we0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st20_fsm_19 or tmp_18_fu_927_p1 or ap_sig_cseq_ST_st13_fsm_12 or tmp_23_fu_1063_p1 or ap_sig_cseq_ST_st27_fsm_26 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st5_fsm_4 or tmp_2_i_fu_887_p1 or tmp_9_i_fu_896_p2 or node_visited_addr_1_gep_fu_198_p3 or tmp_s_fu_902_p1 or tmp_i_fu_983_p1 or tmp_i3_fu_1132_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26)) begin
        node_visited_address0 = tmp_i3_fu_1132_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        node_visited_address0 = tmp_i_fu_983_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        node_visited_address0 = tmp_s_fu_902_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_lv1_0 == tmp_9_i_fu_896_p2))) begin
        node_visited_address0 = node_visited_addr_1_gep_fu_198_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == tmp_9_i_fu_896_p2))) begin
        node_visited_address0 = tmp_2_i_fu_887_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        node_visited_address0 = tmp_23_fu_1063_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        node_visited_address0 = tmp_18_fu_927_p1;
    end else begin
        node_visited_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st20_fsm_19 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st27_fsm_26 or grp_aStar_adjacentNodes_fu_684_ap_done or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st5_fsm_4 or tmp_9_i_fu_896_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) | ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == tmp_9_i_fu_896_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_lv1_0 == tmp_9_i_fu_896_p2)))) begin
        node_visited_ce0 = ap_const_logic_1;
    end else begin
        node_visited_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st27_fsm_26 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st5_fsm_4 or tmp_9_i_fu_896_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_lv1_0 == tmp_9_i_fu_896_p2)))) begin
        node_visited_d0 = ap_const_lv1_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == tmp_9_i_fu_896_p2))) begin
        node_visited_d0 = ap_const_lv1_0;
    end else begin
        node_visited_d0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st13_fsm_12 or exitcond_i1_fu_965_p2 or ap_sig_cseq_ST_st27_fsm_26 or exitcond_i2_fu_1114_p2 or grp_aStar_adjacentNodes_fu_684_ap_done or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st5_fsm_4 or tmp_9_i_fu_896_p2) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~(ap_const_lv1_0 == exitcond_i1_fu_965_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == tmp_9_i_fu_896_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_lv1_0 == tmp_9_i_fu_896_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & ~(ap_const_lv1_0 == exitcond_i2_fu_1114_p2)))) begin
        node_visited_we0 = ap_const_logic_1;
    end else begin
        node_visited_we0 = ap_const_logic_0;
    end
end

always @ (tmp_18_reg_1363 or ap_sig_cseq_ST_st13_fsm_12 or exitcond_i1_fu_965_p2 or tmp_23_reg_1486 or ap_sig_cseq_ST_st27_fsm_26 or exitcond_i2_fu_1114_p2 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st26_fsm_25 or tmp_2_i_fu_887_p1 or tmp_i7_fu_977_p1 or tmp_i_fu_983_p1 or tmp_i8_fu_1126_p1 or tmp_i3_fu_1132_p1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & ~(ap_const_lv1_0 == exitcond_i2_fu_1114_p2))) begin
        openNodes_address0 = tmp_i3_fu_1132_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25)) begin
        openNodes_address0 = tmp_23_reg_1486;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~(ap_const_lv1_0 == exitcond_i1_fu_965_p2))) begin
        openNodes_address0 = tmp_i_fu_983_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        openNodes_address0 = tmp_18_reg_1363;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        openNodes_address0 = tmp_2_i_fu_887_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & (ap_const_lv1_0 == exitcond_i2_fu_1114_p2))) begin
        openNodes_address0 = tmp_i8_fu_1126_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & (ap_const_lv1_0 == exitcond_i1_fu_965_p2))) begin
        openNodes_address0 = tmp_i7_fu_977_p1;
    end else begin
        openNodes_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st13_fsm_12 or exitcond_i1_fu_965_p2 or ap_sig_cseq_ST_st27_fsm_26 or exitcond_i2_fu_1114_p2 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st26_fsm_25) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & (ap_const_lv1_0 == exitcond_i1_fu_965_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~(ap_const_lv1_0 == exitcond_i1_fu_965_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & (ap_const_lv1_0 == exitcond_i2_fu_1114_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25) | ((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & ~(ap_const_lv1_0 == exitcond_i2_fu_1114_p2)))) begin
        openNodes_ce0 = ap_const_logic_1;
    end else begin
        openNodes_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st13_fsm_12 or exitcond_i1_fu_965_p2 or ap_sig_cseq_ST_st27_fsm_26 or exitcond_i2_fu_1114_p2 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st26_fsm_25) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25))) begin
        openNodes_d0 = ap_const_lv1_0;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~(ap_const_lv1_0 == exitcond_i1_fu_965_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | ((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & ~(ap_const_lv1_0 == exitcond_i2_fu_1114_p2)))) begin
        openNodes_d0 = ap_const_lv1_1;
    end else begin
        openNodes_d0 = 'bx;
    end
end

always @ (or_cond_reg_1377 or ap_sig_cseq_ST_st13_fsm_12 or exitcond_i1_fu_965_p2 or or_cond1_reg_1500 or ap_sig_cseq_ST_st27_fsm_26 or exitcond_i2_fu_1114_p2 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st26_fsm_25) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~(ap_const_lv1_0 == exitcond_i1_fu_965_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) & (ap_const_lv1_0 == or_cond_reg_1377)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st26_fsm_25) & (ap_const_lv1_0 == or_cond1_reg_1500)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st27_fsm_26) & ~(ap_const_lv1_0 == exitcond_i2_fu_1114_p2)))) begin
        openNodes_we0 = ap_const_logic_1;
    end else begin
        openNodes_we0 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or exitcond_i_fu_787_p2 or exitcond1_fu_910_p2 or grp_fu_737_p2 or grp_aStar_calculateCost_fu_696_ap_done or exitcond_i1_fu_965_p2 or exitcond_fu_1046_p2 or exitcond_i2_fu_1114_p2 or tmp_26_fu_1185_p2 or grp_aStar_adjacentNodes_fu_684_ap_done or tmp_22_fu_1138_p2) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(exitcond_i_fu_787_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        ap_ST_st5_fsm_4 : 
        begin
            if (~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st6_fsm_5 : 
        begin
            if (~(ap_const_lv1_0 == exitcond1_fu_910_p2)) begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st7_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : 
        begin
            if (~(ap_const_lv1_0 == grp_fu_737_p2)) begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        end
        ap_ST_st9_fsm_8 : 
        begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : 
        begin
            if (~(ap_const_logic_0 == grp_aStar_calculateCost_fu_696_ap_done)) begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end else begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end
        end
        ap_ST_st11_fsm_10 : 
        begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st13_fsm_12 : 
        begin
            if (~(ap_const_lv1_0 == exitcond_i1_fu_965_p2)) begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end else begin
                ap_NS_fsm = ap_ST_st14_fsm_13;
            end
        end
        ap_ST_st14_fsm_13 : 
        begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st15_fsm_14 : 
        begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st16_fsm_15 : 
        begin
            ap_NS_fsm = ap_ST_st17_fsm_16;
        end
        ap_ST_st17_fsm_16 : 
        begin
            ap_NS_fsm = ap_ST_st18_fsm_17;
        end
        ap_ST_st18_fsm_17 : 
        begin
            if (~(ap_const_logic_0 == grp_aStar_adjacentNodes_fu_684_ap_done)) begin
                ap_NS_fsm = ap_ST_st19_fsm_18;
            end else begin
                ap_NS_fsm = ap_ST_st18_fsm_17;
            end
        end
        ap_ST_st19_fsm_18 : 
        begin
            if (~(ap_const_lv1_0 == exitcond_fu_1046_p2)) begin
                ap_NS_fsm = ap_ST_st27_fsm_26;
            end else begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end
        end
        ap_ST_st20_fsm_19 : 
        begin
            ap_NS_fsm = ap_ST_st21_fsm_20;
        end
        ap_ST_st21_fsm_20 : 
        begin
            if (~(ap_const_lv1_0 == grp_fu_737_p2)) begin
                ap_NS_fsm = ap_ST_st26_fsm_25;
            end else begin
                ap_NS_fsm = ap_ST_st22_fsm_21;
            end
        end
        ap_ST_st22_fsm_21 : 
        begin
            ap_NS_fsm = ap_ST_st23_fsm_22;
        end
        ap_ST_st23_fsm_22 : 
        begin
            ap_NS_fsm = ap_ST_st24_fsm_23;
        end
        ap_ST_st24_fsm_23 : 
        begin
            if (~(ap_const_logic_0 == grp_aStar_calculateCost_fu_696_ap_done)) begin
                ap_NS_fsm = ap_ST_st25_fsm_24;
            end else begin
                ap_NS_fsm = ap_ST_st24_fsm_23;
            end
        end
        ap_ST_st25_fsm_24 : 
        begin
            ap_NS_fsm = ap_ST_st26_fsm_25;
        end
        ap_ST_st26_fsm_25 : 
        begin
            ap_NS_fsm = ap_ST_st19_fsm_18;
        end
        ap_ST_st27_fsm_26 : 
        begin
            if ((~(ap_const_lv1_0 == exitcond_i2_fu_1114_p2) & ~(ap_const_lv1_0 == tmp_22_fu_1138_p2))) begin
                ap_NS_fsm = ap_ST_st29_fsm_28;
            end else if (((ap_const_lv1_0 == tmp_22_fu_1138_p2) & ~(ap_const_lv1_0 == exitcond_i2_fu_1114_p2))) begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end else begin
                ap_NS_fsm = ap_ST_st28_fsm_27;
            end
        end
        ap_ST_st28_fsm_27 : 
        begin
            ap_NS_fsm = ap_ST_st27_fsm_26;
        end
        ap_ST_st29_fsm_28 : 
        begin
            ap_NS_fsm = ap_ST_st30_fsm_29;
        end
        ap_ST_st30_fsm_29 : 
        begin
            if (~(ap_const_lv1_0 == tmp_26_fu_1185_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st31_fsm_30;
            end
        end
        ap_ST_st31_fsm_30 : 
        begin
            ap_NS_fsm = ap_ST_st32_fsm_31;
        end
        ap_ST_st32_fsm_31 : 
        begin
            ap_NS_fsm = ap_ST_st29_fsm_28;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign adjacentPosition_0_address1 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_address1;

assign adjacentPosition_0_d0 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_d0;

assign adjacentPosition_0_d1 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_0_d1;

assign adjacentPosition_1_address1 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_address1;

assign adjacentPosition_1_d0 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_d0;

assign adjacentPosition_1_d1 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_1_d1;

assign adjacentPosition_2_address1 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_address1;

assign adjacentPosition_2_d0 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_d0;

assign adjacentPosition_2_d1 = grp_aStar_adjacentNodes_fu_684_adjacentPosition_2_d1;

assign ap_return = ap_const_lv32_0;


always @ (ap_CS_fsm) begin
    ap_sig_bdd_189 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_196 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_13]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_206 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_8]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_213 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_15]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_236 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_257 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_268 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_288 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_303 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_316 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_325 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_347 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_D]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_358 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_E]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_368 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_F]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_378 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_10]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_387 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_12]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_406 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_14]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_420 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_16]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_429 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_18]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_438 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1A]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_456 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1B]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_467 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1C]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_477 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1D]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_48 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_493 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1E]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_549 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_562 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_572 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_598 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_606 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_19]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_622 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1F]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_639 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_17]);
end

assign bestOption_1_bestOption_i1_fu_1156_p3 = ((tmp_8_i1_fu_1143_p2[0:0] === 1'b1) ? node_costPlusHeuristic_q0 : bestOption_i1_reg_663);

assign bestOption_1_bestOption_i_fu_1012_p3 = ((tmp_8_i9_fu_999_p2[0:0] === 1'b1) ? node_costPlusHeuristic_q0 : bestOption_i_reg_605);

assign bestOption_2_i1_fu_1172_p3 = ((openNodes_q0[0:0] === 1'b1) ? bestOption_i1_reg_663 : bestOption_1_bestOption_i1_fu_1156_p3);

assign bestOption_2_i_fu_1028_p3 = ((openNodes_q0[0:0] === 1'b1) ? bestOption_i_reg_605 : bestOption_1_bestOption_i_fu_1012_p3);

assign exitcond1_fu_910_p2 = (i_reg_570 == ap_const_lv4_8? 1'b1: 1'b0);

assign exitcond_fu_1046_p2 = (i1_reg_627 == ap_const_lv4_8? 1'b1: 1'b0);

assign exitcond_i1_fu_965_p2 = (positionBestOption_reg_582 == ap_const_lv12_900? 1'b1: 1'b0);

assign exitcond_i2_fu_1114_p2 = (positionBestOption_1_reg_639 == ap_const_lv12_900? 1'b1: 1'b0);

assign exitcond_i_fu_787_p2 = (i_i_reg_558 == ap_const_lv12_900? 1'b1: 1'b0);

assign extLd_fu_1042_p1 = node_coordinates_0_load_reg_1452;

assign finalPosition_fu_994_p2 = (xFinish + tmp_2_fu_989_p2);

assign grp_aStar_adjacentNodes_fu_684_ap_start = grp_aStar_adjacentNodes_fu_684_ap_start_ap_start_reg;

assign grp_aStar_calculateCost_fu_696_ap_start = grp_aStar_calculateCost_fu_696_ap_start_ap_start_reg;

assign grp_aStar_calculateCost_fu_696_node_cost_q0 = node_cost_q0;

assign grp_aStar_calculateCost_fu_696_node_father_q0 = node_father_q0;

assign grp_aStar_calculateCost_fu_696_position = reg_718;

assign grp_fu_708_p2 = (xFinish - adjacentPosition_0_q0);

assign grp_fu_713_p2 = (yFinish - adjacentPosition_1_q0);

assign grp_fu_731_p2 = (reg_718 == ap_const_lv32_FFFFFFFF? 1'b1: 1'b0);

assign grp_fu_737_p2 = (node_visited_q0 | grp_fu_731_p2);

assign grp_fu_743_p2 = (ap_const_lv32_0 - reg_723);

assign grp_fu_749_p2 = ($signed(reg_723) > $signed(32'b00000000000000000000000000000000)? 1'b1: 1'b0);

assign grp_fu_755_p3 = ((grp_fu_749_p2[0:0] === 1'b1) ? reg_723 : grp_fu_743_p2);

assign grp_fu_763_p2 = (ap_const_lv32_0 - reg_727);

assign grp_fu_769_p2 = ($signed(reg_727) > $signed(32'b00000000000000000000000000000000)? 1'b1: 1'b0);

assign grp_fu_775_p3 = ((grp_fu_769_p2[0:0] === 1'b1) ? reg_727 : grp_fu_763_p2);

assign i_1_fu_793_p2 = (ap_const_lv12_1 + i_i_reg_558);

assign i_2_fu_916_p2 = (i_reg_570 + ap_const_lv4_1);

assign i_3_fu_1052_p2 = (i1_reg_627 + ap_const_lv4_1);

assign i_4_fu_971_p2 = (positionBestOption_reg_582 + ap_const_lv12_1);

assign i_5_fu_1120_p2 = (positionBestOption_1_reg_639 + ap_const_lv12_1);

assign node_coordinates_0_d0 = x_reg_1304;

assign node_coordinates_1_d0 = y_1_reg_1330;

assign node_visited_addr_1_gep_fu_198_p3 = tmp_2_i_fu_887_p1;

assign or_cond_i_fu_811_p2 = (tmp_4_i_fu_799_p2 | tmp_5_i_fu_805_p2);

assign p_shl1_cast_fu_862_p1 = tmp_27_fu_855_p3;

assign p_shl2_cast_fu_1245_p1 = tmp_12_fu_1237_p3;

assign p_shl3_cast_fu_1257_p1 = tmp_13_fu_1249_p3;

assign p_shl4_cast_fu_1197_p3 = {{tmp_9_fu_1194_p1}, {ap_const_lv5_0}};

assign p_shl5_cast_fu_1208_p3 = {{tmp_10_fu_1205_p1}, {ap_const_lv2_0}};

assign p_shl_cast_fu_851_p1 = tmp_16_fu_844_p3;

assign positionBestOption_2_i1_fu_1164_p3 = ((openNodes_q0[0:0] === 1'b1) ? position_4_reg_650 : positionBestOption_positionBes_1_fu_1149_p3);

assign positionBestOption_2_i_fu_1020_p3 = ((openNodes_q0[0:0] === 1'b1) ? position_3_reg_593 : positionBestOption_positionBes_fu_1005_p3);

assign positionBestOption_i11_cast_fu_1110_p1 = positionBestOption_1_reg_639;

assign positionBestOption_i_cast_fu_961_p1 = positionBestOption_reg_582;

assign positionBestOption_positionBes_1_fu_1149_p3 = ((tmp_8_i1_fu_1143_p2[0:0] === 1'b1) ? positionBestOption_i11_cast_reg_1526 : position_4_reg_650);

assign positionBestOption_positionBes_fu_1005_p3 = ((tmp_8_i9_fu_999_p2[0:0] === 1'b1) ? positionBestOption_i_cast_reg_1403 : position_3_reg_593);

assign positionFather_1_fu_1072_p3 = {{tmp_5_fu_1068_p1}, {node_coordinates_0_q0}};

assign position_5_fu_822_p2 = (xStart + tmp_1_fu_817_p2);

assign tmp1_fu_948_p2 = (tmp_3_fu_938_p2 + tmp_4_fu_943_p2);

assign tmp2_fu_1097_p2 = (tmp_7_fu_1092_p2 + tmp_6_fu_1087_p2);

assign tmp_10_fu_1205_p1 = xFinish[10:0];

assign tmp_11_fu_1233_p1 = node_coordinates_1_q0[12:0];

assign tmp_12_fu_1237_p3 = {{node_coordinates_0_q0}, {ap_const_lv5_0}};

assign tmp_13_fu_1249_p3 = {{node_coordinates_0_q0}, {ap_const_lv2_0}};

assign tmp_16_fu_844_p3 = {{x_reg_1304}, {ap_const_lv5_0}};

assign tmp_17_fu_922_p1 = i_reg_570;

assign tmp_18_fu_927_p1 = $signed(adjacentPosition_2_q0);

assign tmp_1_fu_817_p2 = yStart << ap_const_lv32_6;

assign tmp_1_i1_fu_1103_p2 = (node_cost_q0 + tmp2_fu_1097_p2);

assign tmp_1_i_fu_954_p2 = (tmp1_fu_948_p2 + node_cost_q0);

assign tmp_20_fu_1036_p1 = $signed(position3_reg_617);

assign tmp_21_fu_1058_p1 = i1_reg_627;

assign tmp_22_fu_1138_p2 = (position_4_reg_650 == finalPosition_reg_1426? 1'b1: 1'b0);

assign tmp_23_fu_1063_p1 = $signed(adjacentPosition_2_q0);

assign tmp_25_fu_1180_p1 = $signed(position_1_reg_675);

assign tmp_26_fu_1185_p2 = (node_father_q0 == ap_const_lv32_FFFFFFFF? 1'b1: 1'b0);

assign tmp_27_fu_855_p3 = {{x_reg_1304}, {ap_const_lv2_0}};

assign tmp_28_fu_866_p2 = (p_shl_cast_fu_851_p1 + p_shl1_cast_fu_862_p1);

assign tmp_29_fu_876_p2 = (tmp_fu_840_p1 + tmp_34_cast_fu_872_p1);

assign tmp_2_fu_989_p2 = yFinish << ap_const_lv32_6;

assign tmp_2_i_fu_887_p1 = i_i_reg_558;

assign tmp_30_fu_1216_p2 = (p_shl4_cast_fu_1197_p3 + p_shl5_cast_fu_1208_p3);

assign tmp_31_fu_1222_p2 = (tmp_8_fu_1191_p1 + tmp_30_fu_1216_p2);

assign tmp_32_fu_1261_p2 = (p_shl3_cast_fu_1257_p1 + p_shl2_cast_fu_1245_p1);

assign tmp_33_fu_1267_p2 = (tmp_32_fu_1261_p2 + tmp_11_fu_1233_p1);

assign tmp_34_cast_fu_872_p1 = tmp_28_fu_866_p2;

assign tmp_35_cast_fu_882_p1 = $signed(tmp_29_fu_876_p2);

assign tmp_3_fu_938_p2 = tmp_i1_reg_1391 << ap_const_lv32_3;

assign tmp_45_cast_fu_1228_p1 = $signed(tmp_31_fu_1222_p2);

assign tmp_49_cast_fu_1273_p1 = $signed(tmp_33_reg_1591);

assign tmp_4_fu_943_p2 = tmp_i1_reg_1391 << ap_const_lv32_1;

assign tmp_4_i_fu_799_p2 = (x_fu_783_p1 != ap_const_lv6_0? 1'b1: 1'b0);

assign tmp_5_fu_1068_p1 = node_coordinates_1_q0[25:0];

assign tmp_5_i_fu_805_p2 = (i_i_reg_558 == ap_const_lv12_0? 1'b1: 1'b0);

assign tmp_6_fu_1087_p2 = tmp_i5_reg_1514 << ap_const_lv32_3;

assign tmp_7_fu_1092_p2 = tmp_i5_reg_1514 << ap_const_lv32_1;

assign tmp_8_fu_1191_p1 = yFinish[12:0];

assign tmp_8_i1_fu_1143_p2 = ($signed(node_costPlusHeuristic_q0) < $signed(bestOption_i1_reg_663)? 1'b1: 1'b0);

assign tmp_8_i9_fu_999_p2 = ($signed(node_costPlusHeuristic_q0) < $signed(bestOption_i_reg_605)? 1'b1: 1'b0);

assign tmp_9_fu_1194_p1 = xFinish[7:0];

assign tmp_9_i_fu_896_p2 = (map_r_q0 == ap_const_lv32_1? 1'b1: 1'b0);

assign tmp_fu_840_p1 = y_1_fu_833_p3[12:0];

assign tmp_i1_fu_932_p2 = (grp_fu_775_p3 + grp_fu_755_p3);

assign tmp_i3_fu_1132_p1 = $signed(position_4_reg_650);

assign tmp_i5_fu_1081_p2 = (grp_fu_755_p3 + grp_fu_775_p3);

assign tmp_i7_fu_977_p1 = positionBestOption_reg_582;

assign tmp_i8_fu_1126_p1 = positionBestOption_1_reg_639;

assign tmp_i_fu_983_p1 = $signed(position_3_reg_593);

assign tmp_s_fu_902_p1 = $signed(position_5_reg_1324);

assign x_fu_783_p1 = i_i_reg_558[5:0];

assign y_1_fu_833_p3 = ((or_cond_i_reg_1319[0:0] === 1'b1) ? y_i_reg_546 : y_fu_827_p2);

assign y_fu_827_p2 = (ap_const_lv32_1 + y_i_reg_546);
always @ (posedge ap_clk) begin
    tmp_17_reg_1352[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    positionBestOption_i_cast_reg_1403[31:12] <= 20'b00000000000000000000;
    extLd_reg_1462[31:6] <= 26'b00000000000000000000000000;
    tmp_21_reg_1475[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    positionBestOption_i11_cast_reg_1526[31:12] <= 20'b00000000000000000000;
end



endmodule //aStar

