// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module aStar_adjacentNodes (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        y,
        adjacentPosition_2_address0,
        adjacentPosition_2_ce0,
        adjacentPosition_2_we0,
        adjacentPosition_2_d0,
        adjacentPosition_2_address1,
        adjacentPosition_2_ce1,
        adjacentPosition_2_we1,
        adjacentPosition_2_d1,
        adjacentPosition_0_address0,
        adjacentPosition_0_ce0,
        adjacentPosition_0_we0,
        adjacentPosition_0_d0,
        adjacentPosition_0_address1,
        adjacentPosition_0_ce1,
        adjacentPosition_0_we1,
        adjacentPosition_0_d1,
        adjacentPosition_1_address0,
        adjacentPosition_1_ce0,
        adjacentPosition_1_we0,
        adjacentPosition_1_d0,
        adjacentPosition_1_address1,
        adjacentPosition_1_ce1,
        adjacentPosition_1_we1,
        adjacentPosition_1_d1
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 18'b1;
parameter    ap_ST_st2_fsm_1 = 18'b10;
parameter    ap_ST_st3_fsm_2 = 18'b100;
parameter    ap_ST_st4_fsm_3 = 18'b1000;
parameter    ap_ST_st5_fsm_4 = 18'b10000;
parameter    ap_ST_st6_fsm_5 = 18'b100000;
parameter    ap_ST_st7_fsm_6 = 18'b1000000;
parameter    ap_ST_st8_fsm_7 = 18'b10000000;
parameter    ap_ST_st9_fsm_8 = 18'b100000000;
parameter    ap_ST_st10_fsm_9 = 18'b1000000000;
parameter    ap_ST_st11_fsm_10 = 18'b10000000000;
parameter    ap_ST_st12_fsm_11 = 18'b100000000000;
parameter    ap_ST_st13_fsm_12 = 18'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 18'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 18'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 18'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 18'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 18'b100000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv3_6 = 3'b110;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv3_7 = 3'b111;
parameter    ap_const_lv3_3 = 3'b11;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv32_3E = 32'b111110;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_23 = 32'b100011;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_22 = 32'b100010;
parameter    ap_const_lv32_FFFFFFBF = 32'b11111111111111111111111110111111;
parameter    ap_const_lv32_FFFFFFC1 = 32'b11111111111111111111111111000001;
parameter    ap_const_lv32_41 = 32'b1000001;
parameter    ap_const_lv32_FFFFFFC0 = 32'b11111111111111111111111111000000;
parameter    ap_const_lv32_40 = 32'b1000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] x;
input  [31:0] y;
output  [2:0] adjacentPosition_2_address0;
output   adjacentPosition_2_ce0;
output   adjacentPosition_2_we0;
output  [31:0] adjacentPosition_2_d0;
output  [2:0] adjacentPosition_2_address1;
output   adjacentPosition_2_ce1;
output   adjacentPosition_2_we1;
output  [31:0] adjacentPosition_2_d1;
output  [2:0] adjacentPosition_0_address0;
output   adjacentPosition_0_ce0;
output   adjacentPosition_0_we0;
output  [31:0] adjacentPosition_0_d0;
output  [2:0] adjacentPosition_0_address1;
output   adjacentPosition_0_ce1;
output   adjacentPosition_0_we1;
output  [31:0] adjacentPosition_0_d1;
output  [2:0] adjacentPosition_1_address0;
output   adjacentPosition_1_ce0;
output   adjacentPosition_1_we0;
output  [31:0] adjacentPosition_1_d0;
output  [2:0] adjacentPosition_1_address1;
output   adjacentPosition_1_ce1;
output   adjacentPosition_1_we1;
output  [31:0] adjacentPosition_1_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[2:0] adjacentPosition_2_address0;
reg adjacentPosition_2_ce0;
reg adjacentPosition_2_we0;
reg[31:0] adjacentPosition_2_d0;
reg[2:0] adjacentPosition_2_address1;
reg adjacentPosition_2_ce1;
reg adjacentPosition_2_we1;
reg[31:0] adjacentPosition_2_d1;
reg[2:0] adjacentPosition_0_address0;
reg adjacentPosition_0_ce0;
reg adjacentPosition_0_we0;
reg[31:0] adjacentPosition_0_d0;
reg[2:0] adjacentPosition_0_address1;
reg adjacentPosition_0_ce1;
reg adjacentPosition_0_we1;
reg[31:0] adjacentPosition_0_d1;
reg[2:0] adjacentPosition_1_address0;
reg adjacentPosition_1_ce0;
reg adjacentPosition_1_we0;
reg[31:0] adjacentPosition_1_d0;
reg[2:0] adjacentPosition_1_address1;
reg adjacentPosition_1_ce1;
reg adjacentPosition_1_we1;
reg[31:0] adjacentPosition_1_d1;
(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm = 18'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_36;
wire   [31:0] initPosition_fu_177_p2;
reg   [31:0] initPosition_reg_297;
wire   [0:0] tmp_7_fu_233_p2;
reg   [0:0] tmp_7_reg_307;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_92;
wire   [0:0] tmp_8_fu_238_p2;
reg   [0:0] tmp_8_reg_311;
wire   [31:0] tmp_10_fu_243_p2;
reg   [31:0] tmp_10_reg_315;
wire   [31:0] tmp_11_fu_249_p2;
reg   [31:0] tmp_11_reg_320;
wire   [0:0] tmp_12_fu_255_p2;
reg   [0:0] tmp_12_reg_325;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_113;
wire   [0:0] tmp_13_fu_260_p2;
reg   [0:0] tmp_13_reg_329;
wire   [31:0] tmp_14_fu_265_p2;
reg   [31:0] tmp_14_reg_333;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_126;
wire   [31:0] tmp_15_fu_271_p2;
reg   [31:0] tmp_15_reg_339;
wire   [31:0] tmp_3_fu_183_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_136;
wire   [31:0] tmp_5_fu_197_p2;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_145;
wire   [31:0] tmp_s_fu_209_p2;
wire   [31:0] tmp_1_fu_221_p2;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_bdd_156;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_bdd_165;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_bdd_174;
reg    ap_sig_cseq_ST_st15_fsm_14;
reg    ap_sig_bdd_183;
reg    ap_sig_cseq_ST_st16_fsm_15;
reg    ap_sig_bdd_192;
reg    ap_sig_cseq_ST_st18_fsm_17;
reg    ap_sig_bdd_201;
wire   [31:0] tmp_4_fu_190_p2;
wire   [31:0] tmp_6_fu_203_p2;
wire   [31:0] tmp_9_fu_215_p2;
wire   [31:0] tmp_2_fu_227_p2;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_bdd_225;
reg    ap_sig_cseq_ST_st17_fsm_16;
reg    ap_sig_bdd_238;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_260;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_268;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_bdd_324;
reg    ap_sig_cseq_ST_st14_fsm_13;
reg    ap_sig_bdd_332;
wire   [31:0] tmp_fu_171_p2;
reg   [17:0] ap_NS_fsm;




always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        initPosition_reg_297 <= initPosition_fu_177_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (tmp_7_fu_233_p2 == ap_const_lv1_0) & (tmp_8_fu_238_p2 == ap_const_lv1_0))) begin
        tmp_10_reg_315 <= tmp_10_fu_243_p2;
        tmp_11_reg_320 <= tmp_11_fu_249_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        tmp_12_reg_325 <= tmp_12_fu_255_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (ap_const_lv1_0 == tmp_12_fu_255_p2))) begin
        tmp_13_reg_329 <= tmp_13_fu_260_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        tmp_14_reg_333 <= tmp_14_fu_265_p2;
        tmp_15_reg_339 <= tmp_15_fu_271_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        tmp_7_reg_307 <= tmp_7_fu_233_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (tmp_7_fu_233_p2 == ap_const_lv1_0))) begin
        tmp_8_reg_311 <= tmp_8_fu_238_p2;
    end
end

always @ (tmp_7_fu_233_p2 or ap_sig_cseq_ST_st4_fsm_3 or tmp_8_fu_238_p2 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        adjacentPosition_0_address0 = ap_const_lv3_6;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10))) begin
        adjacentPosition_0_address0 = ap_const_lv3_7;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        adjacentPosition_0_address0 = ap_const_lv3_5;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4))) begin
        adjacentPosition_0_address0 = ap_const_lv3_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_7_fu_233_p2 == ap_const_lv1_0))) begin
        adjacentPosition_0_address0 = ap_const_lv3_1;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (tmp_7_fu_233_p2 == ap_const_lv1_0) & (tmp_8_fu_238_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (tmp_7_fu_233_p2 == ap_const_lv1_0) & ~(tmp_8_fu_238_p2 == ap_const_lv1_0)))) begin
        adjacentPosition_0_address0 = ap_const_lv3_0;
    end else begin
        adjacentPosition_0_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        adjacentPosition_0_address1 = ap_const_lv3_5;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        adjacentPosition_0_address1 = ap_const_lv3_6;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5))) begin
        adjacentPosition_0_address1 = ap_const_lv3_4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4))) begin
        adjacentPosition_0_address1 = ap_const_lv3_2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        adjacentPosition_0_address1 = ap_const_lv3_1;
    end else begin
        adjacentPosition_0_address1 = 'bx;
    end
end

always @ (tmp_7_fu_233_p2 or ap_sig_cseq_ST_st4_fsm_3 or tmp_8_fu_238_p2 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (tmp_7_fu_233_p2 == ap_const_lv1_0) & (tmp_8_fu_238_p2 == ap_const_lv1_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (tmp_7_fu_233_p2 == ap_const_lv1_0) & ~(tmp_8_fu_238_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_7_fu_233_p2 == ap_const_lv1_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5))) begin
        adjacentPosition_0_ce0 = ap_const_logic_1;
    end else begin
        adjacentPosition_0_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5))) begin
        adjacentPosition_0_ce1 = ap_const_logic_1;
    end else begin
        adjacentPosition_0_ce1 = ap_const_logic_0;
    end
end

always @ (x or tmp_7_fu_233_p2 or ap_sig_cseq_ST_st4_fsm_3 or tmp_8_fu_238_p2 or tmp_10_fu_243_p2 or tmp_11_reg_320 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        adjacentPosition_0_d0 = ap_const_lv32_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        adjacentPosition_0_d0 = ap_const_lv32_3F;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5))) begin
        adjacentPosition_0_d0 = tmp_11_reg_320;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        adjacentPosition_0_d0 = x;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_7_fu_233_p2 == ap_const_lv1_0)))) begin
        adjacentPosition_0_d0 = ap_const_lv32_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (tmp_7_fu_233_p2 == ap_const_lv1_0) & ~(tmp_8_fu_238_p2 == ap_const_lv1_0)))) begin
        adjacentPosition_0_d0 = ap_const_lv32_3E;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (tmp_7_fu_233_p2 == ap_const_lv1_0) & (tmp_8_fu_238_p2 == ap_const_lv1_0))) begin
        adjacentPosition_0_d0 = tmp_10_fu_243_p2;
    end else begin
        adjacentPosition_0_d0 = 'bx;
    end
end

always @ (x or ap_sig_cseq_ST_st4_fsm_3 or tmp_10_reg_315 or tmp_11_fu_249_p2 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        adjacentPosition_0_d1 = ap_const_lv32_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        adjacentPosition_0_d1 = ap_const_lv32_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        adjacentPosition_0_d1 = ap_const_lv32_3E;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        adjacentPosition_0_d1 = ap_const_lv32_3F;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5))) begin
        adjacentPosition_0_d1 = tmp_10_reg_315;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        adjacentPosition_0_d1 = x;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        adjacentPosition_0_d1 = tmp_11_fu_249_p2;
    end else begin
        adjacentPosition_0_d1 = 'bx;
    end
end

always @ (tmp_7_fu_233_p2 or tmp_7_reg_307 or ap_sig_cseq_ST_st4_fsm_3 or tmp_8_fu_238_p2 or tmp_8_reg_311 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (tmp_7_fu_233_p2 == ap_const_lv1_0) & (tmp_8_fu_238_p2 == ap_const_lv1_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (tmp_7_fu_233_p2 == ap_const_lv1_0) & ~(tmp_8_fu_238_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(tmp_7_fu_233_p2 == ap_const_lv1_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (tmp_7_reg_307 == ap_const_lv1_0) & (tmp_8_reg_311 == ap_const_lv1_0)))) begin
        adjacentPosition_0_we0 = ap_const_logic_1;
    end else begin
        adjacentPosition_0_we0 = ap_const_logic_0;
    end
end

always @ (tmp_7_fu_233_p2 or tmp_7_reg_307 or ap_sig_cseq_ST_st4_fsm_3 or tmp_8_fu_238_p2 or tmp_8_reg_311 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (tmp_7_fu_233_p2 == ap_const_lv1_0) & (tmp_8_fu_238_p2 == ap_const_lv1_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (tmp_7_reg_307 == ap_const_lv1_0) & (tmp_8_reg_311 == ap_const_lv1_0)))) begin
        adjacentPosition_0_we1 = ap_const_logic_1;
    end else begin
        adjacentPosition_0_we1 = ap_const_logic_0;
    end
end

always @ (tmp_12_fu_255_p2 or ap_sig_cseq_ST_st7_fsm_6 or tmp_13_fu_260_p2 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        adjacentPosition_1_address0 = ap_const_lv3_2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13))) begin
        adjacentPosition_1_address0 = ap_const_lv3_7;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        adjacentPosition_1_address0 = ap_const_lv3_5;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16))) begin
        adjacentPosition_1_address0 = ap_const_lv3_3;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (ap_const_lv1_0 == tmp_12_fu_255_p2) & (ap_const_lv1_0 == tmp_13_fu_260_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (ap_const_lv1_0 == tmp_12_fu_255_p2) & ~(ap_const_lv1_0 == tmp_13_fu_260_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_lv1_0 == tmp_12_fu_255_p2)))) begin
        adjacentPosition_1_address0 = ap_const_lv3_0;
    end else begin
        adjacentPosition_1_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13))) begin
        adjacentPosition_1_address1 = ap_const_lv3_6;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12))) begin
        adjacentPosition_1_address1 = ap_const_lv3_4;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        adjacentPosition_1_address1 = ap_const_lv3_2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16))) begin
        adjacentPosition_1_address1 = ap_const_lv3_1;
    end else begin
        adjacentPosition_1_address1 = 'bx;
    end
end

always @ (tmp_12_fu_255_p2 or ap_sig_cseq_ST_st7_fsm_6 or tmp_13_fu_260_p2 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (ap_const_lv1_0 == tmp_12_fu_255_p2) & (ap_const_lv1_0 == tmp_13_fu_260_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (ap_const_lv1_0 == tmp_12_fu_255_p2) & ~(ap_const_lv1_0 == tmp_13_fu_260_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_lv1_0 == tmp_12_fu_255_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13))) begin
        adjacentPosition_1_ce0 = ap_const_logic_1;
    end else begin
        adjacentPosition_1_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13))) begin
        adjacentPosition_1_ce1 = ap_const_logic_1;
    end else begin
        adjacentPosition_1_ce1 = ap_const_logic_0;
    end
end

always @ (y or tmp_12_fu_255_p2 or ap_sig_cseq_ST_st7_fsm_6 or tmp_13_fu_260_p2 or tmp_14_reg_333 or ap_sig_cseq_ST_st12_fsm_11 or tmp_15_fu_271_p2 or tmp_15_reg_339 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16))) begin
        adjacentPosition_1_d0 = ap_const_lv32_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15))) begin
        adjacentPosition_1_d0 = ap_const_lv32_22;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        adjacentPosition_1_d0 = tmp_15_reg_339;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        adjacentPosition_1_d0 = tmp_14_reg_333;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        adjacentPosition_1_d0 = tmp_15_fu_271_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_lv1_0 == tmp_12_fu_255_p2))) begin
        adjacentPosition_1_d0 = ap_const_lv32_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (ap_const_lv1_0 == tmp_12_fu_255_p2) & ~(ap_const_lv1_0 == tmp_13_fu_260_p2))) begin
        adjacentPosition_1_d0 = ap_const_lv32_23;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (ap_const_lv1_0 == tmp_12_fu_255_p2) & (ap_const_lv1_0 == tmp_13_fu_260_p2))) begin
        adjacentPosition_1_d0 = y;
    end else begin
        adjacentPosition_1_d0 = 'bx;
    end
end

always @ (y or ap_sig_cseq_ST_st7_fsm_6 or tmp_14_fu_265_p2 or tmp_14_reg_333 or ap_sig_cseq_ST_st12_fsm_11 or tmp_15_reg_339 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17)) begin
        adjacentPosition_1_d1 = ap_const_lv32_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        adjacentPosition_1_d1 = ap_const_lv32_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15)) begin
        adjacentPosition_1_d1 = ap_const_lv32_22;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        adjacentPosition_1_d1 = ap_const_lv32_23;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        adjacentPosition_1_d1 = tmp_15_reg_339;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        adjacentPosition_1_d1 = tmp_14_reg_333;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        adjacentPosition_1_d1 = tmp_14_fu_265_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        adjacentPosition_1_d1 = y;
    end else begin
        adjacentPosition_1_d1 = 'bx;
    end
end

always @ (tmp_12_fu_255_p2 or tmp_12_reg_325 or ap_sig_cseq_ST_st7_fsm_6 or tmp_13_fu_260_p2 or tmp_13_reg_329 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (ap_const_lv1_0 == tmp_12_fu_255_p2) & (ap_const_lv1_0 == tmp_13_fu_260_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (ap_const_lv1_0 == tmp_12_fu_255_p2) & ~(ap_const_lv1_0 == tmp_13_fu_260_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_lv1_0 == tmp_12_fu_255_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) & (ap_const_lv1_0 == tmp_12_reg_325) & (ap_const_lv1_0 == tmp_13_reg_329)))) begin
        adjacentPosition_1_we0 = ap_const_logic_1;
    end else begin
        adjacentPosition_1_we0 = ap_const_logic_0;
    end
end

always @ (tmp_12_fu_255_p2 or tmp_12_reg_325 or ap_sig_cseq_ST_st7_fsm_6 or tmp_13_fu_260_p2 or tmp_13_reg_329 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & (ap_const_lv1_0 == tmp_12_fu_255_p2) & (ap_const_lv1_0 == tmp_13_fu_260_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) & (ap_const_lv1_0 == tmp_12_reg_325) & (ap_const_lv1_0 == tmp_13_reg_329)))) begin
        adjacentPosition_1_we1 = ap_const_logic_1;
    end else begin
        adjacentPosition_1_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        adjacentPosition_2_address0 = ap_const_lv3_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15))) begin
        adjacentPosition_2_address0 = ap_const_lv3_7;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        adjacentPosition_2_address0 = ap_const_lv3_5;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        adjacentPosition_2_address0 = ap_const_lv3_2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10))) begin
        adjacentPosition_2_address0 = ap_const_lv3_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        adjacentPosition_2_address0 = ap_const_lv3_6;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_2_address0 = ap_const_lv3_4;
    end else begin
        adjacentPosition_2_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st17_fsm_16) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        adjacentPosition_2_address1 = ap_const_lv3_2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15))) begin
        adjacentPosition_2_address1 = ap_const_lv3_6;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        adjacentPosition_2_address1 = ap_const_lv3_4;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        adjacentPosition_2_address1 = ap_const_lv3_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        adjacentPosition_2_address1 = ap_const_lv3_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        adjacentPosition_2_address1 = ap_const_lv3_7;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_2_address1 = ap_const_lv3_5;
    end else begin
        adjacentPosition_2_address1 = 'bx;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) | (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_2_ce0 = ap_const_logic_1;
    end else begin
        adjacentPosition_2_ce0 = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st17_fsm_16) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) | (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16))) begin
        adjacentPosition_2_ce1 = ap_const_logic_1;
    end else begin
        adjacentPosition_2_ce1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st4_fsm_3 or tmp_3_fu_183_p2 or ap_sig_cseq_ST_st2_fsm_1 or tmp_5_fu_197_p2 or ap_sig_cseq_ST_st3_fsm_2 or tmp_s_fu_209_p2 or tmp_1_fu_221_p2 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_2_d0 = ap_const_lv32_FFFFFFFF;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        adjacentPosition_2_d0 = tmp_1_fu_221_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        adjacentPosition_2_d0 = tmp_s_fu_209_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        adjacentPosition_2_d0 = tmp_5_fu_197_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        adjacentPosition_2_d0 = tmp_3_fu_183_p2;
    end else begin
        adjacentPosition_2_d0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or tmp_4_fu_190_p2 or tmp_6_fu_203_p2 or tmp_9_fu_215_p2 or tmp_2_fu_227_p2 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st17_fsm_16) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16))) begin
        adjacentPosition_2_d1 = ap_const_lv32_FFFFFFFF;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        adjacentPosition_2_d1 = tmp_2_fu_227_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        adjacentPosition_2_d1 = tmp_9_fu_215_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        adjacentPosition_2_d1 = tmp_6_fu_203_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        adjacentPosition_2_d1 = tmp_4_fu_190_p2;
    end else begin
        adjacentPosition_2_d1 = 'bx;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) | (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        adjacentPosition_2_we0 = ap_const_logic_1;
    end else begin
        adjacentPosition_2_we0 = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st17_fsm_16) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) | (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16))) begin
        adjacentPosition_2_we1 = ap_const_logic_1;
    end else begin
        adjacentPosition_2_we1 = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st14_fsm_13) begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st14_fsm_13) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_225) begin
    if (ap_sig_bdd_225) begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_174) begin
    if (ap_sig_bdd_174) begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_126) begin
    if (ap_sig_bdd_126) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_324) begin
    if (ap_sig_bdd_324) begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_332) begin
    if (ap_sig_bdd_332) begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_183) begin
    if (ap_sig_bdd_183) begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_192) begin
    if (ap_sig_bdd_192) begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_238) begin
    if (ap_sig_bdd_238) begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_201) begin
    if (ap_sig_bdd_201) begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_36) begin
    if (ap_sig_bdd_36) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_136) begin
    if (ap_sig_bdd_136) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_145) begin
    if (ap_sig_bdd_145) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_92) begin
    if (ap_sig_bdd_92) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_260) begin
    if (ap_sig_bdd_260) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_268) begin
    if (ap_sig_bdd_268) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_113) begin
    if (ap_sig_bdd_113) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_156) begin
    if (ap_sig_bdd_156) begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_165) begin
    if (ap_sig_bdd_165) begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or tmp_7_fu_233_p2 or tmp_8_fu_238_p2 or tmp_12_fu_255_p2 or tmp_13_fu_260_p2) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (((tmp_7_fu_233_p2 == ap_const_lv1_0) & ~(tmp_8_fu_238_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end else if (((tmp_7_fu_233_p2 == ap_const_lv1_0) & (tmp_8_fu_238_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : 
        begin
            if (((ap_const_lv1_0 == tmp_12_fu_255_p2) & ~(ap_const_lv1_0 == tmp_13_fu_260_p2))) begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end else if (((ap_const_lv1_0 == tmp_12_fu_255_p2) & (ap_const_lv1_0 == tmp_13_fu_260_p2))) begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_st17_fsm_16;
            end
        end
        ap_ST_st8_fsm_7 : 
        begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st10_fsm_9 : 
        begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : 
        begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        ap_ST_st15_fsm_14 : 
        begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st16_fsm_15 : 
        begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st17_fsm_16 : 
        begin
            ap_NS_fsm = ap_ST_st18_fsm_17;
        end
        ap_ST_st18_fsm_17 : 
        begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_CS_fsm) begin
    ap_sig_bdd_113 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_126 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_136 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_145 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_156 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_165 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_8]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_174 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_183 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_E]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_192 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_F]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_201 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_225 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_238 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_10]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_260 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_268 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_324 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_332 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_D]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_36 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_92 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

assign initPosition_fu_177_p2 = (x + tmp_fu_171_p2);

assign tmp_10_fu_243_p2 = ($signed(x) + $signed(ap_const_lv32_FFFFFFFF));

assign tmp_11_fu_249_p2 = (x + ap_const_lv32_1);

assign tmp_12_fu_255_p2 = (y == ap_const_lv32_0? 1'b1: 1'b0);

assign tmp_13_fu_260_p2 = (y == ap_const_lv32_23? 1'b1: 1'b0);

assign tmp_14_fu_265_p2 = ($signed(y) + $signed(ap_const_lv32_FFFFFFFF));

assign tmp_15_fu_271_p2 = (y + ap_const_lv32_1);

assign tmp_1_fu_221_p2 = ($signed(ap_const_lv32_FFFFFFC0) + $signed(initPosition_reg_297));

assign tmp_2_fu_227_p2 = (ap_const_lv32_40 + initPosition_reg_297);

assign tmp_3_fu_183_p2 = ($signed(ap_const_lv32_FFFFFFBF) + $signed(initPosition_fu_177_p2));

assign tmp_4_fu_190_p2 = ($signed(ap_const_lv32_FFFFFFC1) + $signed(initPosition_fu_177_p2));

assign tmp_5_fu_197_p2 = (ap_const_lv32_3F + initPosition_reg_297);

assign tmp_6_fu_203_p2 = (ap_const_lv32_41 + initPosition_reg_297);

assign tmp_7_fu_233_p2 = (x == ap_const_lv32_0? 1'b1: 1'b0);

assign tmp_8_fu_238_p2 = (x == ap_const_lv32_3F? 1'b1: 1'b0);

assign tmp_9_fu_215_p2 = (ap_const_lv32_1 + initPosition_reg_297);

assign tmp_fu_171_p2 = y << ap_const_lv32_6;

assign tmp_s_fu_209_p2 = ($signed(ap_const_lv32_FFFFFFFF) + $signed(initPosition_reg_297));


endmodule //aStar_adjacentNodes

