// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "xStart"
#define AUTOTB_TVIN_xStart  "../tv/cdatafile/c.aStar.autotvin_xStart.dat"
// wrapc file define: "yStart"
#define AUTOTB_TVIN_yStart  "../tv/cdatafile/c.aStar.autotvin_yStart.dat"
// wrapc file define: "xFinish"
#define AUTOTB_TVIN_xFinish  "../tv/cdatafile/c.aStar.autotvin_xFinish.dat"
// wrapc file define: "yFinish"
#define AUTOTB_TVIN_yFinish  "../tv/cdatafile/c.aStar.autotvin_yFinish.dat"
// wrapc file define: "map_r"
#define AUTOTB_TVIN_map_r  "../tv/cdatafile/c.aStar.autotvin_map_r.dat"
#define AUTOTB_TVOUT_map_r  "../tv/cdatafile/c.aStar.autotvout_map_r.dat"
// wrapc file define: "ap_return"
#define AUTOTB_TVOUT_ap_return  "../tv/cdatafile/c.aStar.autotvout_ap_return.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "map_r"
#define AUTOTB_TVOUT_PC_map_r  "../tv/rtldatafile/rtl.aStar.autotvout_map_r.dat"
// tvout file define: "ap_return"
#define AUTOTB_TVOUT_PC_ap_return  "../tv/rtldatafile/rtl.aStar.autotvout_ap_return.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			xStart_depth = 0;
			yStart_depth = 0;
			xFinish_depth = 0;
			yFinish_depth = 0;
			map_r_depth = 0;
			ap_return_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{xStart " << xStart_depth << "}\n";
			total_list << "{yStart " << yStart_depth << "}\n";
			total_list << "{xFinish " << xFinish_depth << "}\n";
			total_list << "{yFinish " << yFinish_depth << "}\n";
			total_list << "{map_r " << map_r_depth << "}\n";
			total_list << "{ap_return " << ap_return_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int xStart_depth;
		int yStart_depth;
		int xFinish_depth;
		int yFinish_depth;
		int map_r_depth;
		int ap_return_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};


#define aStar AESL_ORIG_DUT_aStar
extern int aStar (
int xStart,
int yStart,
int xFinish,
int yFinish,
int map[60][34]);
#undef aStar

int aStar (
int xStart,
int yStart,
int xFinish,
int yFinish,
int map[60][34])
{
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		int AESL_return;

		// output port post check: "map_r"
		aesl_fh.read(AUTOTB_TVOUT_PC_map_r, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_map_r, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_map_r, AESL_token); // data

			sc_bv<32> *map_r_pc_buffer = new sc_bv<32>[2040];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'map_r', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'map_r', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					map_r_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_map_r, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_map_r))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: map_r
				{
					// bitslice(31, 0)
					// {
						// celement: map(31, 0)
						// {
							sc_lv<32>* map_lv0_0_59_1_lv1_0_33_1 = new sc_lv<32>[2040];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: map(31, 0)
						{
							// carray: (0) => (59) @ (1)
							for (int i_0 = 0; i_0 <= 59; i_0 += 1)
							{
								// carray: (0) => (33) @ (1)
								for (int i_1 = 0; i_1 <= 33; i_1 += 1)
								{
									if (&(map[0][0]) != NULL) // check the null address if the c port is array or others
									{
										map_lv0_0_59_1_lv1_0_33_1[hls_map_index++].range(31, 0) = sc_bv<32>(map_r_pc_buffer[hls_map_index].range(31, 0));
									}
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: map(31, 0)
						{
							// carray: (0) => (59) @ (1)
							for (int i_0 = 0; i_0 <= 59; i_0 += 1)
							{
								// carray: (0) => (33) @ (1)
								for (int i_1 = 0; i_1 <= 33; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : map[i_0][i_1]
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : map[0][0]
									// output_left_conversion : map[i_0][i_1]
									// output_type_conversion : (map_lv0_0_59_1_lv1_0_33_1[hls_map_index++]).to_uint64()
									if (&(map[0][0]) != NULL) // check the null address if the c port is array or others
									{
										map[i_0][i_1] = (map_lv0_0_59_1_lv1_0_33_1[hls_map_index++]).to_uint64();
									}
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] map_r_pc_buffer;
		}

		// output port post check: "ap_return"
		aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // data

			sc_bv<32> ap_return_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					ap_return_pc_buffer = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_ap_return))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: ap_return
				{
					// bitslice(31, 0)
					// {
						// celement: return(31, 0)
						// {
							sc_lv<32> return_lv0_0_1_0;
						// }
					// }

					// bitslice(31, 0)
					{
						// celement: return(31, 0)
						{
							// carray: (0) => (1) @ (0)
							{
								if (&(AESL_return) != NULL) // check the null address if the c port is array or others
								{
									return_lv0_0_1_0.range(31, 0) = sc_bv<32>(ap_return_pc_buffer.range(31, 0));
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						// celement: return(31, 0)
						{
							// carray: (0) => (1) @ (0)
							{
								// sub                    : 
								// ori_name               : AESL_return
								// sub_1st_elem           : 
								// ori_name_1st_elem      : AESL_return
								// output_left_conversion : AESL_return
								// output_type_conversion : (return_lv0_0_1_0).to_uint64()
								if (&(AESL_return) != NULL) // check the null address if the c port is array or others
								{
									AESL_return = (return_lv0_0_1_0).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		AESL_transaction_pc++;

		return AESL_return;
	}
	else
	{
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "xStart"
		char* tvin_xStart = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_xStart);

		// "yStart"
		char* tvin_yStart = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_yStart);

		// "xFinish"
		char* tvin_xFinish = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_xFinish);

		// "yFinish"
		char* tvin_yFinish = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_yFinish);

		// "map_r"
		char* tvin_map_r = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_map_r);
		char* tvout_map_r = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_map_r);

		// "ap_return"
		char* tvout_ap_return = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_ap_return);

		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_xStart, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_xStart, tvin_xStart);

		sc_bv<32> xStart_tvin_wrapc_buffer;

		// RTL Name: xStart
		{
			// bitslice(31, 0)
			{
				// celement: xStart(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : xStart
						// sub_1st_elem          : 
						// ori_name_1st_elem     : xStart
						// regulate_c_name       : xStart
						// input_type_conversion : xStart
						if (&(xStart) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> xStart_tmp_mem;
							xStart_tmp_mem = xStart;
							xStart_tvin_wrapc_buffer.range(31, 0) = xStart_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_xStart, "%s\n", (xStart_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_xStart, tvin_xStart);
		}

		tcl_file.set_num(1, &tcl_file.xStart_depth);
		sprintf(tvin_xStart, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_xStart, tvin_xStart);

		// [[transaction]]
		sprintf(tvin_yStart, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_yStart, tvin_yStart);

		sc_bv<32> yStart_tvin_wrapc_buffer;

		// RTL Name: yStart
		{
			// bitslice(31, 0)
			{
				// celement: yStart(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : yStart
						// sub_1st_elem          : 
						// ori_name_1st_elem     : yStart
						// regulate_c_name       : yStart
						// input_type_conversion : yStart
						if (&(yStart) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> yStart_tmp_mem;
							yStart_tmp_mem = yStart;
							yStart_tvin_wrapc_buffer.range(31, 0) = yStart_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_yStart, "%s\n", (yStart_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_yStart, tvin_yStart);
		}

		tcl_file.set_num(1, &tcl_file.yStart_depth);
		sprintf(tvin_yStart, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_yStart, tvin_yStart);

		// [[transaction]]
		sprintf(tvin_xFinish, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_xFinish, tvin_xFinish);

		sc_bv<32> xFinish_tvin_wrapc_buffer;

		// RTL Name: xFinish
		{
			// bitslice(31, 0)
			{
				// celement: xFinish(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : xFinish
						// sub_1st_elem          : 
						// ori_name_1st_elem     : xFinish
						// regulate_c_name       : xFinish
						// input_type_conversion : xFinish
						if (&(xFinish) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> xFinish_tmp_mem;
							xFinish_tmp_mem = xFinish;
							xFinish_tvin_wrapc_buffer.range(31, 0) = xFinish_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_xFinish, "%s\n", (xFinish_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_xFinish, tvin_xFinish);
		}

		tcl_file.set_num(1, &tcl_file.xFinish_depth);
		sprintf(tvin_xFinish, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_xFinish, tvin_xFinish);

		// [[transaction]]
		sprintf(tvin_yFinish, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_yFinish, tvin_yFinish);

		sc_bv<32> yFinish_tvin_wrapc_buffer;

		// RTL Name: yFinish
		{
			// bitslice(31, 0)
			{
				// celement: yFinish(31, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : yFinish
						// sub_1st_elem          : 
						// ori_name_1st_elem     : yFinish
						// regulate_c_name       : yFinish
						// input_type_conversion : yFinish
						if (&(yFinish) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> yFinish_tmp_mem;
							yFinish_tmp_mem = yFinish;
							yFinish_tvin_wrapc_buffer.range(31, 0) = yFinish_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_yFinish, "%s\n", (yFinish_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_yFinish, tvin_yFinish);
		}

		tcl_file.set_num(1, &tcl_file.yFinish_depth);
		sprintf(tvin_yFinish, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_yFinish, tvin_yFinish);

		// [[transaction]]
		sprintf(tvin_map_r, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_map_r, tvin_map_r);

		sc_bv<32>* map_r_tvin_wrapc_buffer = new sc_bv<32>[2040];

		// RTL Name: map_r
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: map(31, 0)
				{
					// carray: (0) => (59) @ (1)
					for (int i_0 = 0; i_0 <= 59; i_0 += 1)
					{
						// carray: (0) => (33) @ (1)
						for (int i_1 = 0; i_1 <= 33; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : map[i_0][i_1]
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : map[0][0]
							// regulate_c_name       : map
							// input_type_conversion : map[i_0][i_1]
							if (&(map[0][0]) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<32> map_tmp_mem;
								map_tmp_mem = map[i_0][i_1];
								map_r_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = map_tmp_mem.range(31, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 2040; i++)
		{
			sprintf(tvin_map_r, "%s\n", (map_r_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_map_r, tvin_map_r);
		}

		tcl_file.set_num(2040, &tcl_file.map_r_depth);
		sprintf(tvin_map_r, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_map_r, tvin_map_r);

		// release memory allocation
		delete [] map_r_tvin_wrapc_buffer;

// [call_c_dut] ---------->

		int AESL_return = AESL_ORIG_DUT_aStar(xStart, yStart, xFinish, yFinish, map);


		// [[transaction]]
		sprintf(tvout_map_r, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_map_r, tvout_map_r);

		sc_bv<32>* map_r_tvout_wrapc_buffer = new sc_bv<32>[2040];

		// RTL Name: map_r
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: map(31, 0)
				{
					// carray: (0) => (59) @ (1)
					for (int i_0 = 0; i_0 <= 59; i_0 += 1)
					{
						// carray: (0) => (33) @ (1)
						for (int i_1 = 0; i_1 <= 33; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : map[i_0][i_1]
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : map[0][0]
							// regulate_c_name       : map
							// input_type_conversion : map[i_0][i_1]
							if (&(map[0][0]) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<32> map_tmp_mem;
								map_tmp_mem = map[i_0][i_1];
								map_r_tvout_wrapc_buffer[hls_map_index++].range(31, 0) = map_tmp_mem.range(31, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 2040; i++)
		{
			sprintf(tvout_map_r, "%s\n", (map_r_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_map_r, tvout_map_r);
		}

		tcl_file.set_num(2040, &tcl_file.map_r_depth);
		sprintf(tvout_map_r, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_map_r, tvout_map_r);

		// release memory allocation
		delete [] map_r_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_ap_return, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

		sc_bv<32> ap_return_tvout_wrapc_buffer;

		// RTL Name: ap_return
		{
			// bitslice(31, 0)
			{
				// celement: return(31, 0)
				{
					// carray: (0) => (1) @ (0)
					{
						// sub                   : 
						// ori_name              : AESL_return
						// sub_1st_elem          : 
						// ori_name_1st_elem     : AESL_return
						// regulate_c_name       : return
						// input_type_conversion : AESL_return
						if (&(AESL_return) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> return_tmp_mem;
							return_tmp_mem = AESL_return;
							ap_return_tvout_wrapc_buffer.range(31, 0) = return_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_ap_return, "%s\n", (ap_return_tvout_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);
		}

		tcl_file.set_num(1, &tcl_file.ap_return_depth);
		sprintf(tvout_ap_return, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

		// release memory allocation: "xStart"
		delete [] tvin_xStart;
		// release memory allocation: "yStart"
		delete [] tvin_yStart;
		// release memory allocation: "xFinish"
		delete [] tvin_xFinish;
		// release memory allocation: "yFinish"
		delete [] tvin_yFinish;
		// release memory allocation: "map_r"
		delete [] tvin_map_r;
		delete [] tvout_map_r;
		// release memory allocation: "ap_return"
		delete [] tvout_ap_return;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);

		return AESL_return;
	}
}

